<?php

$countries = [
  "AF" => "Afghanistan",
  "AX" => "Åland Islands",
  "AL" => "Albania",
  "DZ" => "Algeria",
  "AS" => "American Samoa",
  "AD" => "Andorra",
  "AO" => "Angola",
  "AI" => "Anguilla",
  "AQ" => "Antarctica",
  "AG" => "Antigua and Barbuda",
  "AR" => "Argentina",
  "AM" => "Armenia",
  "AW" => "Aruba",
  "AU" => "Australia",
  "AT" => "Austria",
  "AZ" => "Azerbaijan",
  "BS" => "The Bahamas",
  "BH" => "Bahrain",
  "BD" => "Bangladesh",
  "BB" => "Barbados",
  "BY" => "Belarus",
  "BE" => "Belgium",
  "BZ" => "Belize",
  "BJ" => "Benin",
  "BM" => "Bermuda",
  "BT" => "Bhutan",
  "BO" => "Bolivia",
  "BQ" => "Bonaire",
  "BA" => "Bosnia and Herzegovina",
  "BW" => "Botswana",
  "BV" => "Bouvet Island",
  "BR" => "Brazil",
  "IO" => "British Indian Ocean Territory",
  "UM" => "United States Minor Outlying Islands",
  "VG" => "Virgin Islands (British)",
  "VI" => "Virgin Islands (U.S.)",
  "BN" => "Brunei",
  "BG" => "Bulgaria",
  "BF" => "Burkina Faso",
  "BI" => "Burundi",
  "KH" => "Cambodia",
  "CM" => "Cameroon",
  "CA" => "Canada",
  "CV" => "Cape Verde",
  "KY" => "Cayman Islands",
  "CF" => "Central African Republic",
  "TD" => "Chad",
  "CL" => "Chile",
  "CN" => "China",
  "CX" => "Christmas Island",
  "CC" => "Cocos (Keeling) Islands",
  "CO" => "Colombia",
  "KM" => "Comoros",
  "CG" => "Republic of the Congo",
  "CD" => "Democratic Republic of the Congo",
  "CK" => "Cook Islands",
  "CR" => "Costa Rica",
  "HR" => "Croatia",
  "CU" => "Cuba",
  "CW" => "Curaçao",
  "CY" => "Cyprus",
  "CZ" => "Czech Republic",
  "DK" => "Denmark",
  "DJ" => "Djibouti",
  "DM" => "Dominica",
  "DO" => "Dominican Republic",
  "EC" => "Ecuador",
  "EG" => "Egypt",
  "SV" => "El Salvador",
  "GQ" => "Equatorial Guinea",
  "ER" => "Eritrea",
  "EE" => "Estonia",
  "ET" => "Ethiopia",
  "FK" => "Falkland Islands",
  "FO" => "Faroe Islands",
  "FJ" => "Fiji",
  "FI" => "Finland",
  "FR" => "France",
  "GF" => "French Guiana",
  "PF" => "French Polynesia",
  "TF" => "French Southern and Antarctic Lands",
  "GA" => "Gabon",
  "GM" => "The Gambia",
  "GE" => "Georgia",
  "DE" => "Germany",
  "GH" => "Ghana",
  "GI" => "Gibraltar",
  "GR" => "Greece",
  "GL" => "Greenland",
  "GD" => "Grenada",
  "GP" => "Guadeloupe",
  "GU" => "Guam",
  "GT" => "Guatemala",
  "GG" => "Guernsey",
  "GN" => "Guinea",
  "GW" => "Guinea-Bissau",
  "GY" => "Guyana",
  "HT" => "Haiti",
  "HM" => "Heard Island and McDonald Islands",
  "VA" => "Holy See",
  "HN" => "Honduras",
  "HK" => "Hong Kong",
  "HU" => "Hungary",
  "IS" => "Iceland",
  "IN" => "India",
  "ID" => "Indonesia",
  "CI" => "Ivory Coast",
  "IR" => "Iran",
  "IQ" => "Iraq",
  "IE" => "Republic of Ireland",
  "IM" => "Isle of Man",
  "IL" => "Israel",
  "IT" => "Italy",
  "JM" => "Jamaica",
  "JP" => "Japan",
  "JE" => "Jersey",
  "JO" => "Jordan",
  "KZ" => "Kazakhstan",
  "KE" => "Kenya",
  "KI" => "Kiribati",
  "KW" => "Kuwait",
  "KG" => "Kyrgyzstan",
  "LA" => "Laos",
  "LV" => "Latvia",
  "LB" => "Lebanon",
  "LS" => "Lesotho",
  "LR" => "Liberia",
  "LY" => "Libya",
  "LI" => "Liechtenstein",
  "LT" => "Lithuania",
  "LU" => "Luxembourg",
  "MO" => "Macau",
  "MK" => "Republic of Macedonia",
  "MG" => "Madagascar",
  "MW" => "Malawi",
  "MY" => "Malaysia",
  "MV" => "Maldives",
  "ML" => "Mali",
  "MT" => "Malta",
  "MH" => "Marshall Islands",
  "MQ" => "Martinique",
  "MR" => "Mauritania",
  "MU" => "Mauritius",
  "YT" => "Mayotte",
  "MX" => "Mexico",
  "FM" => "Federated States of Micronesia",
  "MD" => "Moldova",
  "MC" => "Monaco",
  "MN" => "Mongolia",
  "ME" => "Montenegro",
  "MS" => "Montserrat",
  "MA" => "Morocco",
  "MZ" => "Mozambique",
  "MM" => "Myanmar",
  "NA" => "Namibia",
  "NR" => "Nauru",
  "NP" => "Nepal",
  "NL" => "Netherlands",
  "NC" => "New Caledonia",
  "NZ" => "New Zealand",
  "NI" => "Nicaragua",
  "NE" => "Niger",
  "NG" => "Nigeria",
  "NU" => "Niue",
  "NF" => "Norfolk Island",
  "KP" => "North Korea",
  "MP" => "Northern Mariana Islands",
  "NO" => "Norway",
  "OM" => "Oman",
  "PK" => "Pakistan",
  "PW" => "Palau",
  "PS" => "Palestine",
  "PA" => "Panama",
  "PG" => "Papua New Guinea",
  "PY" => "Paraguay",
  "PE" => "Peru",
  "PH" => "Philippines",
  "PN" => "Pitcairn Islands",
  "PL" => "Poland",
  "PT" => "Portugal",
  "PR" => "Puerto Rico",
  "QA" => "Qatar",
  "XK" => "Republic of Kosovo",
  "RE" => "Réunion",
  "RO" => "Romania",
  "RU" => "Russia",
  "RW" => "Rwanda",
  "BL" => "Saint Barthélemy",
  "SH" => "Saint Helena",
  "KN" => "Saint Kitts and Nevis",
  "LC" => "Saint Lucia",
  "MF" => "Saint Martin",
  "PM" => "Saint Pierre and Miquelon",
  "VC" => "Saint Vincent and the Grenadines",
  "WS" => "Samoa",
  "SM" => "San Marino",
  "ST" => "São Tomé and Príncipe",
  "SA" => "Saudi Arabia",
  "SN" => "Senegal",
  "RS" => "Serbia",
  "SC" => "Seychelles",
  "SL" => "Sierra Leone",
  "SG" => "Singapore",
  "SX" => "Sint Maarten",
  "SK" => "Slovakia",
  "SI" => "Slovenia",
  "SB" => "Solomon Islands",
  "SO" => "Somalia",
  "ZA" => "South Africa",
  "GS" => "South Georgia",
  "KR" => "South Korea",
  "SS" => "South Sudan",
  "ES" => "Spain",
  "LK" => "Sri Lanka",
  "SD" => "Sudan",
  "SR" => "Suricountry",
  "SJ" => "Svalbard and Jan Mayen",
  "SZ" => "Swaziland",
  "SE" => "Sweden",
  "CH" => "Switzerland",
  "SY" => "Syria",
  "TW" => "Taiwan",
  "TJ" => "Tajikistan",
  "TZ" => "Tanzania",
  "TH" => "Thailand",
  "TL" => "East Timor",
  "TG" => "Togo",
  "TK" => "Tokelau",
  "TO" => "Tonga",
  "TT" => "Trinidad and Tobago",
  "TN" => "Tunisia",
  "TR" => "Turkey",
  "TM" => "Turkmenistan",
  "TC" => "Turks and Caicos Islands",
  "TV" => "Tuvalu",
  "UG" => "Uganda",
  "UA" => "Ukraine",
  "AE" => "United Arab Emirates",
  "GB" => "United Kingdom",
  "US" => "United States",
  "UY" => "Uruguay",
  "UZ" => "Uzbekistan",
  "VU" => "Vanuatu",
  "VE" => "Venezuela",
  "VN" => "Vietnam",
  "WF" => "Wallis and Futuna",
  "EH" => "Western Sahara",
  "YE" => "Yemen",
  "ZM" => "Zambia",
  "ZW" => "Zimbabwe"
];

$states = [
  "AF" => [
    "Badakhshān",
    "Baghlān",
    "Balkh",
    "Bādghīs",
    "Bāmyān",
    "Dāykundī",
    "Farāh",
    "Fāryāb",
    "Ghaznī",
    "Ghōr",
    "Helmand",
    "Herāt",
    "Jowzjān",
    "Kandahār",
    "Khōst",
    "Kunar",
    "Kunduz",
    "Kābul",
    "Kāpīsā",
    "Laghmān",
    "Lōgar",
    "Nangarhār",
    "Nīmrōz",
    "Nūristān",
    "Paktiyā",
    "Paktīkā",
    "Panjshayr",
    "Parwān",
    "Samangān",
    "Sar-e Pul",
    "Takhār",
    "Uruzgān",
    "Wardak",
    "Zābul"
  ],
  "AX" => [
    "N/A"
  ],
  "AL" => [
    "Berat",
    "Dibër",
    "Durrës",
    "Elbasan",
    "Fier",
    "Gjirokastër",
    "Korçë",
    "Kukës",
    "Lezhë",
    "Shkodër",
    "Tiranë",
    "Vlorë"
  ],
  "DZ" => [
    "Adrar",
    "Alger",
    "Annaba",
    "Aïn Defla",
    "Aïn Témouchent",
    "Batna",
    "Biskra",
    "Blida",
    "Bordj Bou Arréridj",
    "Bouira",
    "Boumerdès",
    "Béchar",
    "Béjaïa",
    "Chlef",
    "Constantine",
    "Djelfa",
    "El Bayadh",
    "El Oued",
    "El Tarf",
    "Ghardaïa",
    "Guelma",
    "Illizi",
    "Jijel",
    "Khenchela",
    "Laghouat",
    "Mascara",
    "Mila",
    "Mostaganem",
    "Msila",
    "Médéa",
    "Naama",
    "Oran",
    "Ouargla",
    "Oum el Bouaghi",
    "Relizane",
    "Saïda",
    "Sidi Bel Abbès",
    "Skikda",
    "Souk Ahras",
    "Sétif",
    "Tamanghasset",
    "Tiaret",
    "Tindouf",
    "Tipaza",
    "Tissemsilt",
    "Tizi Ouzou",
    "Tlemcen",
    "Tébessa"
  ],
  "AS" => [
    "N/A"
  ],
  "AD" => [
    "Andorra la Vella",
    "Canillo",
    "Encamp",
    "Escaldes-Engordany",
    "La Massana",
    "Ordino",
    "Sant Julià de Lòria"
  ],
  "AO" => [
    "Bengo",
    "Benguela",
    "Bié",
    "Cabinda",
    "Cunene",
    "Huambo",
    "Huíla",
    "Kuando Kubango",
    "Kwanza Norte",
    "Kwanza Sul",
    "Luanda",
    "Lunda Norte",
    "Lunda Sul",
    "Malange",
    "Moxico",
    "Namibe",
    "Uíge",
    "Zaire"
  ],
  "AI" => [
    "N/A"
  ],
  "AQ" => [
    "N/A"
  ],
  "AG" => [
    "Barbuda",
    "Redonda",
    "Saint George",
    "Saint John",
    "Saint Mary",
    "Saint Paul",
    "Saint Peter",
    "Saint Philip"
  ],
  "AR" => [
    "Buenos Aires",
    "Catamarca",
    "Chaco",
    "Chubut",
    "Ciudad Autónoma de Buenos Aires",
    "Corrientes",
    "Córdoba",
    "Entre Ríos",
    "Formosa",
    "Jujuy",
    "La Pampa",
    "La Rioja",
    "Mendoza",
    "Misiones",
    "Neuquén",
    "Río Negro",
    "Salta",
    "San Juan",
    "San Luis",
    "Santa Cruz",
    "Santa Fe",
    "Santiago del Estero",
    "Tierra del Fuego",
    "Tucumán"
  ],
  "AM" => [
    "Aragac̣otn",
    "Ararat",
    "Armavir",
    "Erevan",
    "Geġark'unik'",
    "Kotayk'",
    "Loṙi",
    "Syunik'",
    "Tavuš",
    "Vayoć Jor",
    "Širak"
  ],
  "AW" => [
    "N/A"
  ],
  "AU" => [
    "Australian Capital Territory",
    "New South Wales",
    "Northern Territory",
    "Queensland",
    "South Australia",
    "Tasmania",
    "Victoria",
    "Western Australia"
  ],
  "AT" => [
    "Burgenland",
    "Kärnten",
    "Niederösterreich",
    "Oberösterreich",
    "Salzburg",
    "Steiermark",
    "Tirol",
    "Vorarlberg",
    "Wien"
  ],
  "AZ" => [
    "Naxçivan"
  ],
  "BS" => [
    "Acklins",
    "Berry Islands",
    "Bimini",
    "Black Point",
    "Cat Island",
    "Central Abaco",
    "Central Andros",
    "Central Eleuthera",
    "City of Freeport",
    "Crooked Island and Long Cay",
    "East Grand Bahama",
    "Exuma",
    "Grand Cay",
    "Harbour Island",
    "Hope Town",
    "Inagua",
    "Long Island",
    "Mangrove Cay",
    "Mayaguana",
    "Moores Island",
    "North Abaco",
    "North Andros",
    "North Eleuthera",
    "Ragged Island",
    "Rum Cay",
    "San Salvador",
    "South Abaco",
    "South Andros",
    "South Eleuthera",
    "Spanish Wells",
    "West Grand Bahama"
  ],
  "BH" => [
    "Al Janūbīyah",
    "Al Manāmah",
    "Al Muḩarraq",
    "Al Wusţá",
    "Ash Shamālīyah"
  ],
  "BD" => [
    "Barisal",
    "Chittagong",
    "Dhaka",
    "Khulna",
    "Rajshahi",
    "Rangpur",
    "Sylhet"
  ],
  "BB" => [
    "Christ Church",
    "Saint Andrew",
    "Saint George",
    "Saint James",
    "Saint John",
    "Saint Joseph",
    "Saint Lucy",
    "Saint Michael",
    "Saint Peter",
    "Saint Philip",
    "Saint Thomas"
  ],
  "BY" => [
    "Brestskaya voblasts'",
    "Homyel'skaya voblasts'",
    "Horad Minsk",
    "Hrodzenskaya voblasts'",
    "Mahilyowskaya voblasts'",
    "Minskaya voblasts'",
    "Vitsyebskaya voblasts'"
  ],
  "BE" => [
    "Brussels Hoofdstedelijk Gewest",
    "Région Wallonne",
    "Vlaams Gewest"
  ],
  "BZ" => [
    "Belize",
    "Cayo",
    "Corozal",
    "Orange Walk",
    "Stann Creek",
    "Toledo"
  ],
  "BJ" => [
    "Alibori",
    "Atakora",
    "Atlantique",
    "Borgou",
    "Collines",
    "Donga",
    "Kouffo",
    "Littoral",
    "Mono",
    "Ouémé",
    "Plateau",
    "Zou"
  ],
  "BM" => [
    "N/A"
  ],
  "BT" => [
    "Bumthang",
    "Chhukha",
    "Dagana",
    "Gasa",
    "Ha",
    "Lhuentse",
    "Monggar",
    "Paro",
    "Pemagatshel",
    "Punakha",
    "Samdrup Jongkha",
    "Samtse",
    "Sarpang",
    "Thimphu",
    "Trashi Yangtse",
    "Trashigang",
    "Trongsa",
    "Tsirang",
    "Wangdue Phodrang",
    "Zhemgang"
  ],
  "BO" => [
    "Chuquisaca",
    "Cochabamba",
    "El Beni",
    "La Paz",
    "Oruro",
    "Pando",
    "Potosí",
    "Santa Cruz",
    "Tarija"
  ],
  "BQ" => [
    "N/A"
  ],
  "BA" => [
    "Brčko distrikt",
    "Federacija Bosna i Hercegovina",
    "Republika Srpska"
  ],
  "BW" => [
    "Central",
    "Chobe",
    "Francistown",
    "Gaborone",
    "Ghanzi",
    "Jwaneng",
    "Kgalagadi",
    "Kgatleng",
    "Kweneng",
    "Lobatse",
    "North-East",
    "North-West",
    "Selibe Phikwe",
    "South-East",
    "Southern",
    "Sowa Town"
  ],
  "BV" => [
    "N/A"
  ],
  "BR" => [
    "Acre",
    "Alagoas",
    "Amapá",
    "Amazonas",
    "Bahia",
    "Ceará",
    "Distrito Federal",
    "Espírito Santo",
    "Goiás",
    "Maranhão",
    "Mato Grosso",
    "Mato Grosso do Sul",
    "Minas Gerais",
    "Paraná",
    "Paraíba",
    "Pará",
    "Pernambuco",
    "Piauí",
    "Rio Grande do Norte",
    "Rio Grande do Sul",
    "Rio de Janeiro",
    "Rondônia",
    "Roraima",
    "Santa Catarina",
    "Sergipe",
    "São Paulo",
    "Tocantins"
  ],
  "IO" => [
    "N/A"
  ],
  "UM" => [
    "Baker Island",
    "Howland Island",
    "Jarvis Island",
    "Johnston Atoll",
    "Kingman Reef",
    "Midway Islands",
    "Navassa Island",
    "Palmyra Atoll",
    "Wake Island"
  ],
  "VG" => [
    "N/A"
  ],
  "VI" => [
    "N/A"
  ],
  "BN" => [
    "Belait",
    "Brunei-Muara",
    "Temburong",
    "Tutong"
  ],
  "BG" => [
    "Blagoevgrad",
    "Burgas",
    "Dobrich",
    "Gabrovo",
    "Haskovo",
    "Kardzhali",
    "Kyustendil",
    "Lovech",
    "Montana",
    "Pazardzhik",
    "Pernik",
    "Pleven",
    "Plovdiv",
    "Razgrad",
    "Ruse",
    "Shumen",
    "Silistra",
    "Sliven",
    "Smolyan",
    "Sofia",
    "Sofia-Grad",
    "Stara Zagora",
    "Targovishte",
    "Varna",
    "Veliko Tarnovo",
    "Vidin",
    "Vratsa",
    "Yambol"
  ],
  "BF" => [
    "Boucle du Mouhoun",
    "Cascades",
    "Centre",
    "Centre-Est",
    "Centre-Nord",
    "Centre-Ouest",
    "Centre-Sud",
    "Est",
    "Hauts-Bassins",
    "Nord",
    "Plateau-Central",
    "Sahel",
    "Sud-Ouest"
  ],
  "BI" => [
    "Bubanza",
    "Bujumbura Mairie",
    "Bujumbura Rural",
    "Bururi",
    "Cankuzo",
    "Cibitoke",
    "Gitega",
    "Karuzi",
    "Kayanza",
    "Kirundo",
    "Makamba",
    "Muramvya",
    "Muyinga",
    "Mwaro",
    "Ngozi",
    "Rutana",
    "Ruyigi"
  ],
  "KH" => [
    "Baat Dambang",
    "Banteay Mean Chey",
    "Kampong Chaam",
    "Kampong Chhnang",
    "Kampong Spueu",
    "Kampong Thum",
    "Kampot",
    "Kandaal",
    "Kaoh Kong",
    "Kracheh",
    "Krong Kaeb",
    "Krong Pailin",
    "Krong Preah Sihanouk",
    "Mondol Kiri",
    "Otdar Mean Chey",
    "Phnom Penh",
    "Pousaat",
    "Preah Vihear",
    "Prey Veaeng",
    "Rotanak Kiri",
    "Siem Reab",
    "Stueng Traeng",
    "Svaay Rieng",
    "Taakaev"
  ],
  "CM" => [
    "Adamaoua",
    "Centre",
    "East",
    "Far North",
    "Littoral",
    "North",
    "North-West",
    "South",
    "South-West",
    "West"
  ],
  "CA" => [
    "Alberta",
    "British Columbia",
    "Manitoba",
    "New Brunswick",
    "Newfoundland and Labrador",
    "Nova Scotia",
    "Ontario",
    "Prince Edward Island",
    "Quebec",
    "Saskatchewan",
    "Northwest Territories",
    "Nunavut",
    "Yukon"
  ],
  "CV" => [
    "Ilhas de Barlavento",
    "Ilhas de Sotavento"
  ],
  "KY" => [
    "N/A"
  ],
  "CF" => [
    "Bamingui-Bangoran",
    "Bangui",
    "Basse-Kotto",
    "Gribingui",
    "Haut-Mbomou",
    "Haute-Kotto",
    "Haute-Sangha / Mambéré-Kadéï",
    "Kémo-Gribingui",
    "Lobaye",
    "Mbomou",
    "Nana-Mambéré",
    "Ombella-Mpoko",
    "Ouaka",
    "Ouham",
    "Ouham-Pendé",
    "Sangha",
    "Vakaga"
  ],
  "TD" => [
    "Al Baṭḩah",
    "Al Buḩayrah",
    "Baḩr al Ghazāl",
    "Būrkū",
    "Innīdī",
    "Kānim",
    "Lūqūn al Gharbī",
    "Lūqūn ash Sharqī",
    "Madīnat Injamīnā",
    "Māndūl",
    "Māyū Kībbī al Gharbī",
    "Māyū Kībbī ash Sharqī",
    "Qīrā",
    "Salāmāt",
    "Shārī Bāqirmī",
    "Shārī al Awsaṭ",
    "Sīlā",
    "Tibastī",
    "Tānjilī",
    "Waddāy",
    "Wādī Fīrā",
    "Ḥajjar Lamīs"
  ],
  "CL" => [
    "Aisén del General Carlos Ibañez del Campo",
    "Antofagasta",
    "Araucanía",
    "Arica y Parinacota",
    "Atacama",
    "Bío-Bío",
    "Coquimbo",
    "Libertador General Bernardo O'Higgins",
    "Los Lagos",
    "Los Ríos",
    "Magallanes",
    "Maule",
    "Región Metropolitana de Santiago",
    "Tarapacá",
    "Valparaíso"
  ],
  "CN" => [
    "Guangxi",
    "Nei Mongol",
    "Ningxia",
    "Xinjiang",
    "Xizang",
    "Beijing",
    "Chongqing",
    "Shanghai",
    "Tianjin",
    "Anhui",
    "Fujian",
    "Gansu",
    "Guangdong",
    "Guizhou",
    "Hainan",
    "Hebei",
    "Heilongjiang",
    "Henan",
    "Hubei",
    "Hunan",
    "Jiangsu",
    "Jiangxi",
    "Jilin",
    "Liaoning",
    "Qinghai",
    "Shaanxi",
    "Shandong",
    "Shanxi",
    "Sichuan",
    "Taiwan",
    "Yunnan",
    "Zhejiang",
    "Hong Kong",
    "Macao",
    "Hong Kong Island",
    "Kowloon",
    "New Territories"
  ],
  "CX" => [
    "N/A"
  ],
  "CC" => [
    "N/A"
  ],
  "CO" => [
    "Amazonas",
    "Antioquia",
    "Arauca",
    "Atlántico",
    "Bolívar",
    "Boyacá",
    "Caldas",
    "Caquetá",
    "Casanare",
    "Cauca",
    "Cesar",
    "Chocó",
    "Cundinamarca",
    "Córdoba",
    "Distrito Capital de Bogotá",
    "Guainía",
    "Guaviare",
    "Huila",
    "La Guajira",
    "Magdalena",
    "Meta",
    "Nariño",
    "Norte de Santander",
    "Putumayo",
    "Quindío",
    "Risaralda",
    "San Andrés, Providencia y Santa Catalina",
    "Santander",
    "Sucre",
    "Tolima",
    "Valle del Cauca",
    "Vaupés",
    "Vichada"
  ],
  "KM" => [
    "Anjouan",
    "Grande Comore",
    "Mohéli"
  ],
  "CG" => [
    "Bouenza",
    "Brazzaville",
    "Cuvette",
    "Cuvette-Ouest",
    "Kouilou",
    "Likouala",
    "Lékoumou",
    "Niari",
    "Plateaux",
    "Pointe-Noire",
    "Pool",
    "Sangha"
  ],
  "CD" => [
    "Bandundu",
    "Bas-Congo",
    "Kasai-Occidental",
    "Kasai-Oriental",
    "Katanga",
    "Kinshasa",
    "Maniema",
    "Nord-Kivu",
    "Orientale",
    "Sud-Kivu",
    "Équateur"
  ],
  "CK" => [
    "N/A"
  ],
  "CR" => [
    "Alajuela",
    "Cartago",
    "Guanacaste",
    "Heredia",
    "Limón",
    "Puntarenas",
    "San José"
  ],
  "HR" => [
    "Bjelovarsko-bilogorska županija",
    "Brodsko-posavska županija",
    "Dubrovačko-neretvanska županija",
    "Grad Zagreb",
    "Istarska županija",
    "Karlovačka županija",
    "Koprivničko-križevačka županija",
    "Krapinsko-zagorska županija",
    "Ličko-senjska županija",
    "Međimurska županija",
    "Osječko-baranjska županija",
    "Požeško-slavonska županija",
    "Primorsko-goranska županija",
    "Sisačko-moslavačka županija",
    "Splitsko-dalmatinska županija",
    "Varaždinska županija",
    "Virovitičko-podravska županija",
    "Vukovarsko-srijemska županija",
    "Zadarska županija",
    "Zagrebačka županija",
    "Šibensko-kninska županija"
  ],
  "CU" => [
    "Artemisa",
    "Camagüey",
    "Ciego de Ávila",
    "Cienfuegos",
    "Granma",
    "Guantánamo",
    "Holguín",
    "Isla de la Juventud",
    "La Habana",
    "Las Tunas",
    "Matanzas",
    "Mayabeque",
    "Pinar del Río",
    "Sancti Spíritus",
    "Santiago de Cuba",
    "Villa Clara"
  ],
  "CW" => [
    "N/A"
  ],
  "CY" => [
    "Ammochostos",
    "Keryneia",
    "Larnaka",
    "Lefkosia",
    "Lemesos",
    "Pafos"
  ],
  "CZ" => [
    "Jihomoravský kraj",
    "Jihočeský kraj",
    "Karlovarský kraj",
    "Královéhradecký kraj",
    "Liberecký kraj",
    "Moravskoslezský kraj",
    "Olomoucký kraj",
    "Pardubický kraj",
    "Plzeňský kraj",
    "Praha, hlavní město",
    "Středočeský kraj",
    "Vysočina",
    "Zlínský kraj",
    "Ústecký kraj"
  ],
  "DK" => [
    "Hovedstaden",
    "Midtjylland",
    "Nordjylland",
    "Sjælland",
    "Syddanmark"
  ],
  "DJ" => [
    "Ali Sabieh",
    "Arta",
    "Dikhil",
    "Djibouti",
    "Obock",
    "Tadjourah"
  ],
  "DM" => [
    "Saint Andrew",
    "Saint David",
    "Saint George",
    "Saint John",
    "Saint Joseph",
    "Saint Luke",
    "Saint Mark",
    "Saint Patrick",
    "Saint Paul",
    "Saint Peter"
  ],
  "DO" => [
    "Cibao Nordeste",
    "Cibao Noroeste",
    "Cibao Norte",
    "Cibao Sur",
    "El Valle",
    "Enriquillo",
    "Higuamo",
    "Ozama",
    "Valdesia",
    "Yuma"
  ],
  "EC" => [
    "Azuay",
    "Bolívar",
    "Carchi",
    "Cañar",
    "Chimborazo",
    "Cotopaxi",
    "El Oro",
    "Esmeraldas",
    "Galápagos",
    "Guayas",
    "Imbabura",
    "Loja",
    "Los Ríos",
    "Manabí",
    "Morona-Santiago",
    "Napo",
    "Orellana",
    "Pastaza",
    "Pichincha",
    "Santa Elena",
    "Santo Domingo de los Tsáchilas",
    "Sucumbíos",
    "Tungurahua",
    "Zamora-Chinchipe"
  ],
  "EG" => [
    "Ad Daqahlīyah",
    "Al Baḩr al Aḩmar",
    "Al Buḩayrah",
    "Al Fayyūm",
    "Al Gharbīyah",
    "Al Iskandarīyah",
    "Al Ismāٰīlīyah",
    "Al Jīzah",
    "Al Minyā",
    "Al Minūfīyah",
    "Al Qalyūbīyah",
    "Al Qāhirah",
    "Al Uqşur",
    "Al Wādī al Jadīd",
    "As Suways",
    "As Sādis min Uktūbar",
    "Ash Sharqīyah",
    "Aswān",
    "Asyūţ",
    "Banī Suwayf",
    "Būr Saٰīd",
    "Dumyāţ",
    "Janūb Sīnā'",
    "Kafr ash Shaykh",
    "Maţrūḩ",
    "Qinā",
    "Shamāl Sīnā'",
    "Sūhāj",
    "Ḩulwān"
  ],
  "SV" => [
    "Ahuachapán",
    "Cabañas",
    "Chalatenango",
    "Cuscatlán",
    "La Libertad",
    "La Paz",
    "La Unión",
    "Morazán",
    "San Miguel",
    "San Salvador",
    "San Vicente",
    "Santa Ana",
    "Sonsonate",
    "Usulután"
  ],
  "GQ" => [
    "Región Continental",
    "Región Insular"
  ],
  "ER" => [
    "Al Awsaţ",
    "Al Janūbĩ",
    "Ansabā",
    "Janūbī al Baḩrī al Aḩmar",
    "Qāsh-Barkah",
    "Shimālī al Baḩrī al Aḩmar"
  ],
  "EE" => [
    "Harjumaa",
    "Hiiumaa",
    "Ida-Virumaa",
    "Järvamaa",
    "Jõgevamaa",
    "Lääne-Virumaa",
    "Läänemaa",
    "Pärnumaa",
    "Põlvamaa",
    "Raplamaa",
    "Saaremaa",
    "Tartumaa",
    "Valgamaa",
    "Viljandimaa",
    "Võrumaa"
  ],
  "ET" => [
    "Bīnshangul Gumuz",
    "Dirē Dawa",
    "Gambēla Hizboch",
    "Hārerī Hizb",
    "Oromīya",
    "Sumalē",
    "Tigray",
    "YeDebub Bihēroch Bihēreseboch na Hizboch",
    "Ādīs Ābeba",
    "Āfar",
    "Āmara"
  ],
  "FK" => [
    "N/A"
  ],
  "FO" => [
    "N/A"
  ],
  "FJ" => [
    "Central",
    "Eastern",
    "Northern",
    "Rotuma",
    "Western"
  ],
  "FI" => [
    "Ahvenanmaan maakunta",
    "Etelä-Karjala",
    "Etelä-Pohjanmaa",
    "Etelä-Savo",
    "Kainuu",
    "Kanta-Häme",
    "Keski-Pohjanmaa",
    "Keski-Suomi",
    "Kymenlaakso",
    "Lappi",
    "Pirkanmaa",
    "Pohjanmaa",
    "Pohjois-Karjala",
    "Pohjois-Pohjanmaa",
    "Pohjois-Savo",
    "Päijät-Häme",
    "Satakunta",
    "Uusimaa",
    "Varsinais-Suomi"
  ],
  "FR" => [
    "Alsace",
    "Aquitaine",
    "Auvergne",
    "Brittany",
    "Burgundy",
    "Centre-Val de Loire",
    "Champagne-Ardenne",
    "Corsica",
    "Franche-Comté",
    "Languedoc-Roussillon",
    "Limousin",
    "Lorraine",
    "Lower Normandy",
    "Midi-Pyrénées",
    "Nord-Pas-de-Calais",
    "Pays de la Loire",
    "Picardy",
    "Poitou-Charentes",
    "Provence-Alpes-Côte d'Azur",
    "Rhône-Alpes",
    "Upper Normandy",
    "Île-de-France"
  ],
  "GF" => [
    "N/A"
  ],
  "PF" => [
    "N/A"
  ],
  "TF" => [
    "N/A"
  ],
  "GA" => [
    "Estuaire",
    "Haut-Ogooué",
    "Moyen-Ogooué",
    "Ngounié",
    "Nyanga",
    "Ogooué-Ivindo",
    "Ogooué-Lolo",
    "Ogooué-Maritime",
    "Woleu-Ntem"
  ],
  "GM" => [
    "Banjul",
    "Central River",
    "Lower River",
    "North Bank",
    "Upper River",
    "Western"
  ],
  "GE" => [
    "Abkhazia",
    "Ajaria",
    "Guria",
    "Imereti",
    "K'akheti",
    "Kvemo Kartli",
    "Mtskheta-Mtianeti",
    "Rach'a-Lechkhumi-Kvemo Svaneti",
    "Samegrelo-Zemo Svaneti",
    "Samtskhe-Javakheti",
    "Shida Kartli",
    "Tbilisi"
  ],
  "DE" => [
    "Baden-Württemberg",
    "Bayern",
    "Berlin",
    "Brandenburg",
    "Bremen",
    "Hamburg",
    "Hessen",
    "Mecklenburg-Vorpommern",
    "Niedersachsen",
    "Nordrhein-Westfalen",
    "Rheinland-Pfalz",
    "Saarland",
    "Sachsen",
    "Sachsen-Anhalt",
    "Schleswig-Holstein",
    "Thüringen"
  ],
  "GH" => [
    "Ashanti",
    "Brong-Ahafo",
    "Central",
    "Eastern",
    "Greater Accra",
    "Northern",
    "Upper East",
    "Upper West",
    "Volta",
    "Western"
  ],
  "GI" => [
    "N/A"
  ],
  "GR" => [
    "Anatoliki Makedonia kai Thraki",
    "Attiki",
    "Dytiki Ellada",
    "Dytiki Makedonia",
    "Ionia Nisia",
    "Ipeiros",
    "Kentriki Makedonia",
    "Kriti",
    "Notio Aigaio",
    "Peloponnisos",
    "Sterea Ellada",
    "Thessalia",
    "Voreio Aigaio"
  ],
  "GL" => [
    "Kommune Kujalleq",
    "Kommuneqarfik Sermersooq",
    "Qaasuitsup Kommunia",
    "Qeqqata Kommunia"
  ],
  "GD" => [
    "Saint Andrew",
    "Saint David",
    "Saint George",
    "Saint John",
    "Saint Mark",
    "Saint Patrick",
    "Southern Grenadine Islands"
  ],
  "GP" => [
    "N/A"
  ],
  "GU" => [
    "N/A"
  ],
  "GT" => [
    "Alta Verapaz",
    "Baja Verapaz",
    "Chimaltenango",
    "Chiquimula",
    "El Progreso",
    "Escuintla",
    "Guatemala",
    "Huehuetenango",
    "Izabal",
    "Jalapa",
    "Jutiapa",
    "Petén",
    "Quetzaltenango",
    "Quiché",
    "Retalhuleu",
    "Sacatepéquez",
    "San Marcos",
    "Santa Rosa",
    "Sololá",
    "Suchitepéquez",
    "Totonicapán",
    "Zacapa"
  ],
  "GG" => [
    "N/A"
  ],
  "GN" => [
    "Boké",
    "Conakry",
    "Faranah",
    "Kankan",
    "Kindia",
    "Labé",
    "Mamou",
    "Nzérékoré"
  ],
  "GW" => [
    "Leste",
    "Norte",
    "Sul"
  ],
  "GY" => [
    "Barima-Waini",
    "Cuyuni-Mazaruni",
    "Demerara-Mahaica",
    "East Berbice-Corentyne",
    "Essequibo Islands-West Demerara",
    "Mahaica-Berbice",
    "Pomeroon-Supenaam",
    "Potaro-Siparuni",
    "Upper Demerara-Berbice",
    "Upper Takutu-Upper Essequibo"
  ],
  "HT" => [
    "Artibonite",
    "Centre",
    "Grande-Anse",
    "Nippes",
    "Nord",
    "Nord-Est",
    "Nord-Ouest",
    "Ouest",
    "Sud",
    "Sud-Est"
  ],
  "HM" => [
    "N/A"
  ],
  "VA" => [
    "N/A"
  ],
  "HN" => [
    "Atlántida",
    "Choluteca",
    "Colón",
    "Comayagua",
    "Copán",
    "Cortés",
    "El Paraíso",
    "Francisco Morazán",
    "Gracias a Dios",
    "Intibucá",
    "Islas de la Bahía",
    "La Paz",
    "Lempira",
    "Ocotepeque",
    "Olancho",
    "Santa Bárbara",
    "Valle",
    "Yoro"
  ],
  "HK" => [
    "N/A"
  ],
  "HU" => [
    "Baranya",
    "Borsod-Abaúj-Zemplén",
    "Budapest",
    "Bács-Kiskun",
    "Békés",
    "Békéscsaba",
    "Csongrád",
    "Debrecen",
    "Dunaújváros",
    "Eger",
    "Fejér",
    "Győr",
    "Győr-Moson-Sopron",
    "Hajdú-Bihar",
    "Heves",
    "Hódmezővásárhely",
    "Jász-Nagykun-Szolnok",
    "Kaposvár",
    "Kecskemét",
    "Komárom-Esztergom",
    "Miskolc",
    "Nagykanizsa",
    "Nyíregyháza",
    "Nógrád",
    "Pest",
    "Pécs",
    "Salgótarján",
    "Somogy",
    "Sopron",
    "Szabolcs-Szatmár-Bereg",
    "Szeged",
    "Szekszárd",
    "Szolnok",
    "Szombathely",
    "Székesfehérvár",
    "Tatabánya",
    "Tolna",
    "Vas",
    "Veszprém",
    "Veszprém",
    "Zala",
    "Zalaegerszeg",
    "Érd"
  ],
  "IS" => [
    "Austurland",
    "Höfuðborgarsvæði utan Reykjavíkur",
    "Norðurland eystra",
    "Norðurland vestra",
    "Reykjavík",
    "Suðurland",
    "Suðurnes",
    "Vestfirðir",
    "Vesturland"
  ],
  "IN" => [
    "Andaman and Nicobar Islands",
    "Chandigarh",
    "Dadra and Nagar Haveli",
    "Daman and Diu",
    "Delhi",
    "Lakshadweep",
    "Puducherry",
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jammu and Kashmir",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal"
  ],
  "ID" => [
    "Jawa",
    "Kalimantan",
    "Maluku",
    "Nusa Tenggara",
    "Papua",
    "Sulawesi",
    "Sumatera"
  ],
  "CI" => [
    "18 Montagnes",
    "Agnébi",
    "Bafing",
    "Bas-Sassandra",
    "Denguélé",
    "Fromager",
    "Haut-Sassandra",
    "Lacs",
    "Lagunes",
    "Marahoué",
    "Moyen-Cavally",
    "Moyen-Comoé",
    "Nzi-Comoé",
    "Savanes",
    "Sud-Bandama",
    "Sud-Comoé",
    "Vallée du Bandama",
    "Worodougou",
    "Zanzan"
  ],
  "IR" => [
    "Alborz",
    "Ardabīl",
    "Būshehr",
    "Chahār Maḩāll va Bakhtīārī",
    "Eşfahān",
    "Fārs",
    "Golestān",
    "Gīlān",
    "Hamadān",
    "Hormozgān",
    "Kermān",
    "Kermānshāh",
    "Khorāsān-e Janūbī",
    "Khorāsān-e Razavī",
    "Khorāsān-e Shemālī",
    "Khūzestān",
    "Kohgīlūyeh va Būyer Aḩmad",
    "Kordestān",
    "Lorestān",
    "Markazī",
    "Māzandarān",
    "Qazvīn",
    "Qom",
    "Semnān",
    "Sīstān va Balūchestān",
    "Tehrān",
    "Yazd",
    "Zanjān",
    "Āz̄arbāyjān-e Gharbī",
    "Āz̄arbāyjān-e Sharqī",
    "Īlām"
  ],
  "IQ" => [
    "Al Anbār",
    "Al Başrah",
    "Al Muthanná",
    "Al Qādisīyah",
    "An Najaf",
    "Arbīl",
    "As Sulaymānīyah",
    "At Ta'mīm",
    "Baghdād",
    "Bābil",
    "Dahūk",
    "Dhī Qār",
    "Diyālá",
    "Karbalā'",
    "Maysān",
    "Nīnawá",
    "Wāsiţ",
    "Şalāḩ ad Dīn"
  ],
  "IE" => [
    "Connaught",
    "Leinster",
    "Munster",
    "Ulster"
  ],
  "IM" => [
    "N/A"
  ],
  "IL" => [
    "HaDarom",
    "HaMerkaz",
    "HaTsafon",
    "H̱efa",
    "Tel-Aviv",
    "Yerushalayim"
  ],
  "IT" => [
    "Abruzzo",
    "Basilicata",
    "Calabria",
    "Campania",
    "Emilia-Romagna",
    "Friuli-Venezia Giulia",
    "Lazio",
    "Liguria",
    "Lombardia",
    "Marche",
    "Molise",
    "Piemonte",
    "Puglia",
    "Sardegna",
    "Sicilia",
    "Toscana",
    "Trentino-Alto Adige",
    "Umbria",
    "Valle d'Aosta",
    "Veneto"
  ],
  "JM" => [
    "Clarendon",
    "Hanover",
    "Kingston",
    "Manchester",
    "Portland",
    "Saint Andrew",
    "Saint Ann",
    "Saint Catherine",
    "Saint Elizabeth",
    "Saint James",
    "Saint Mary",
    "Saint Thomas",
    "Trelawny",
    "Westmoreland"
  ],
  "JP" => [
    "Aiti",
    "Akita",
    "Aomori",
    "Ehime",
    "Gihu",
    "Gunma",
    "Hirosima",
    "Hokkaidô",
    "Hukui",
    "Hukuoka",
    "Hukusima",
    "Hyôgo",
    "Ibaraki",
    "Isikawa",
    "Iwate",
    "Kagawa",
    "Kagosima",
    "Kanagawa",
    "Kumamoto",
    "Kyôto",
    "Kôti",
    "Mie",
    "Miyagi",
    "Miyazaki",
    "Nagano",
    "Nagasaki",
    "Nara",
    "Niigata",
    "Okayama",
    "Okinawa",
    "Saga",
    "Saitama",
    "Siga",
    "Simane",
    "Sizuoka",
    "Tiba",
    "Tokusima",
    "Totigi",
    "Tottori",
    "Toyama",
    "Tôkyô",
    "Wakayama",
    "Yamagata",
    "Yamaguti",
    "Yamanasi",
    "Ôita",
    "Ôsaka"
  ],
  "JE" => [
    "N/A"
  ],
  "JO" => [
    "Al Balqā'",
    "Al 'Aqabah",
    "Az Zarqā'",
    "Aţ Ţafīlah",
    "Irbid",
    "Jerash",
    "Karak",
    "Ma'ān",
    "Mafraq",
    "Mādabā",
    "'Ajlūn",
    "'Ammān"
  ],
  "KZ" => [
    "Almaty",
    "Almaty oblysy",
    "Aqmola oblysy",
    "Aqtöbe oblysy",
    "Astana",
    "Atyraū oblysy",
    "Batys Qazaqstan oblysy",
    "Mangghystaū oblysy",
    "Ongtüstik Qazaqstan oblysy",
    "Pavlodar oblysy",
    "Qaraghandy oblysy",
    "Qostanay oblysy",
    "Qyzylorda oblysy",
    "Shyghys Qazaqstan oblysy",
    "Soltüstik Qazaqstan oblysy",
    "Zhambyl oblysy"
  ],
  "KE" => [
    "Central",
    "Coast",
    "Eastern",
    "Nairobi",
    "North-Eastern",
    "Nyanza",
    "Rift Valley",
    "Western"
  ],
  "KI" => [
    "Gilbert Islands",
    "Line Islands",
    "Phoenix Islands"
  ],
  "KW" => [
    "Al Aḩmadi",
    "Al Farwānīyah",
    "Al Jahrā'",
    "Al Kuwayt",
    "Mubārak al Kabīr",
    "Ḩawallī"
  ],
  "KG" => [
    "Batken",
    "Bishkek",
    "Chü",
    "Jalal-Abad",
    "Naryn",
    "Osh",
    "Talas",
    "Ysyk-Köl"
  ],
  "LA" => [
    "Attapu",
    "Bokèo",
    "Bolikhamxai",
    "Champasak",
    "Houaphan",
    "Khammouan",
    "Louang Namtha",
    "Louangphabang",
    "Oudômxai",
    "Phôngsali",
    "Salavan",
    "Savannakhét",
    "Vientiane",
    "Vientiane",
    "Xaignabouli",
    "Xaisômboun",
    "Xiangkhoang",
    "Xékong"
  ],
  "LV" => [
    "Aglonas novads",
    "Aizkraukles novads",
    "Aizputes novads",
    "Aknīstes novads",
    "Alojas novads",
    "Alsungas novads",
    "Alūksnes novads",
    "Amatas novads",
    "Apes novads",
    "Auces novads",
    "Babītes novads",
    "Baldones novads",
    "Baltinavas novads",
    "Balvu novads",
    "Bauskas novads",
    "Beverīnas novads",
    "Brocēnu novads",
    "Burtnieku novads",
    "Carnikavas novads",
    "Cesvaines novads",
    "Ciblas novads",
    "Cēsu novads",
    "Dagdas novads",
    "Daugavpils",
    "Daugavpils novads",
    "Dobeles novads",
    "Dundagas novads",
    "Durbes novads",
    "Engures novads",
    "Garkalnes novads",
    "Grobiņas novads",
    "Gulbenes novads",
    "Iecavas novads",
    "Ikšķiles novads",
    "Ilūkstes novads",
    "Inčukalna novads",
    "Jaunjelgavas novads",
    "Jaunpiebalgas novads",
    "Jaunpils novads",
    "Jelgava",
    "Jelgavas novads",
    "Jēkabpils",
    "Jēkabpils novads",
    "Jūrmala",
    "Kandavas novads",
    "Kocēnu novads",
    "Kokneses novads",
    "Krimuldas novads",
    "Krustpils novads",
    "Krāslavas novads",
    "Kuldīgas novads",
    "Kārsavas novads",
    "Lielvārdes novads",
    "Liepāja",
    "Limbažu novads",
    "Lubānas novads",
    "Ludzas novads",
    "Līgatnes novads",
    "Līvānu novads",
    "Madonas novads",
    "Mazsalacas novads",
    "Mālpils novads",
    "Mārupes novads",
    "Mērsraga novads",
    "Naukšēnu novads",
    "Neretas novads",
    "Nīcas novads",
    "Ogres novads",
    "Olaines novads",
    "Ozolnieku novads",
    "Preiļu novads",
    "Priekules novads",
    "Priekuļu novads",
    "Pārgaujas novads",
    "Pāvilostas novads",
    "Pļaviņu novads",
    "Raunas novads",
    "Riebiņu novads",
    "Rojas novads",
    "Ropažu novads",
    "Rucavas novads",
    "Rugāju novads",
    "Rundāles novads",
    "Rēzekne",
    "Rēzeknes novads",
    "Rīga",
    "Rūjienas novads",
    "Salacgrīvas novads",
    "Salas novads",
    "Salaspils novads",
    "Saldus novads",
    "Saulkrastu novads",
    "Siguldas novads",
    "Skrundas novads",
    "Skrīveru novads",
    "Smiltenes novads",
    "Stopiņu novads",
    "Strenču novads",
    "Sējas novads",
    "Talsu novads",
    "Tukuma novads",
    "Tērvetes novads",
    "Vaiņodes novads",
    "Valkas novads",
    "Valmiera",
    "Varakļānu novads",
    "Vecpiebalgas novads",
    "Vecumnieku novads",
    "Ventspils",
    "Ventspils novads",
    "Viesītes novads",
    "Viļakas novads",
    "Viļānu novads",
    "Vārkavas novads",
    "Zilupes novads",
    "Ādažu novads",
    "Ērgļu novads",
    "Ķeguma novads",
    "Ķekavas novads"
  ],
  "LB" => [
    "Aakkâr",
    "Baalbek-Hermel",
    "Beyrouth",
    "Béqaa",
    "Liban-Nord",
    "Liban-Sud",
    "Mont-Liban",
    "Nabatîyé"
  ],
  "LS" => [
    "Berea",
    "Butha-Buthe",
    "Leribe",
    "Mafeteng",
    "Maseru",
    "Mohale's Hoek",
    "Mokhotlong",
    "Qacha's Nek",
    "Quthing",
    "Thaba-Tseka"
  ],
  "LR" => [
    "Bomi",
    "Bong",
    "Gbarpolu",
    "Grand Bassa",
    "Grand Cape Mount",
    "Grand Gedeh",
    "Grand Kru",
    "Lofa",
    "Margibi",
    "Maryland",
    "Montserrado",
    "Nimba",
    "River Gee",
    "Rivercess",
    "Sinoe"
  ],
  "LY" => [
    "Al Buţnān",
    "Al Jabal al Akhḑar",
    "Al Jabal al Gharbī",
    "Al Jifārah",
    "Al Jufrah",
    "Al Kufrah",
    "Al Marj",
    "Al Marqab",
    "Al Wāḩāt",
    "An Nuqaţ al Khams",
    "Az Zāwiyah",
    "Banghāzī",
    "Darnah",
    "Ghāt",
    "Mişrātah",
    "Murzuq",
    "Nālūt",
    "Sabhā",
    "Surt",
    "Wādī al Ḩayāt",
    "Wādī ash Shāţi'",
    "Ţarābulus"
  ],
  "LI" => [
    "Balzers",
    "Eschen",
    "Gamprin",
    "Mauren",
    "Planken",
    "Ruggell",
    "Schaan",
    "Schellenberg",
    "Triesen",
    "Triesenberg",
    "Vaduz"
  ],
  "LT" => [
    "Alytaus Apskritis",
    "Kauno Apskritis",
    "Klaipėdos Apskritis",
    "Marijampolės Apskritis",
    "Panevėžio Apskritis",
    "Tauragės Apskritis",
    "Telšių Apskritis",
    "Utenos Apskritis",
    "Vilniaus Apskritis",
    "Šiaulių Apskritis"
  ],
  "LU" => [
    "Diekirch",
    "Grevenmacher",
    "Luxembourg"
  ],
  "MO" => [
    "N/A"
  ],
  "MK" => [
    "Aerodrom",
    "Aračinovo",
    "Berovo",
    "Bitola",
    "Bogdanci",
    "Bogovinje",
    "Bosilovo",
    "Brvenica",
    "Butel",
    "Centar",
    "Centar Župa",
    "Debar",
    "Debarca",
    "Delčevo",
    "Demir Hisar",
    "Demir Kapija",
    "Dojran",
    "Dolneni",
    "Drugovo",
    "Gazi Baba",
    "Gevgelija",
    "Gjorče Petrov",
    "Gostivar",
    "Gradsko",
    "Ilinden",
    "Jegunovce",
    "Karbinci",
    "Karpoš",
    "Kavadarci",
    "Kisela Voda",
    "Kičevo",
    "Konče",
    "Kočani",
    "Kratovo",
    "Kriva Palanka",
    "Krivogaštani",
    "Kruševo",
    "Kumanovo",
    "Lipkovo",
    "Lozovo",
    "Makedonska Kamenica",
    "Makedonski Brod",
    "Mavrovo i Rostuša",
    "Mogila",
    "Negotino",
    "Novaci",
    "Novo Selo",
    "Ohrid",
    "Oslomej",
    "Pehčevo",
    "Petrovec",
    "Plasnica",
    "Prilep",
    "Probištip",
    "Radoviš",
    "Rankovce",
    "Resen",
    "Rosoman",
    "Saraj",
    "Sopište",
    "Staro Nagoričane",
    "Struga",
    "Strumica",
    "Studeničani",
    "Sveti Nikole",
    "Tearce",
    "Tetovo",
    "Valandovo",
    "Vasilevo",
    "Veles",
    "Vevčani",
    "Vinica",
    "Vraneštica",
    "Vrapčište",
    "Zajas",
    "Zelenikovo",
    "Zrnovci",
    "Čair",
    "Čaška",
    "Češinovo-Obleševo",
    "Čučer Sandevo",
    "Štip",
    "Šuto Orizari",
    "Želino"
  ],
  "MG" => [
    "Antananarivo",
    "Antsiranana",
    "Fianarantsoa",
    "Mahajanga",
    "Toamasina",
    "Toliara"
  ],
  "MW" => [
    "Central Region",
    "Northern Region",
    "Southern Region"
  ],
  "MY" => [
    "Wilayah Persekutuan Kuala Lumpur",
    "Wilayah Persekutuan Labuan",
    "Wilayah Persekutuan Putrajaya",
    "Johor",
    "Kedah",
    "Kelantan",
    "Melaka",
    "Negeri Sembilan",
    "Pahang",
    "Perak",
    "Perlis",
    "Pulau Pinang",
    "Sabah",
    "Sarawak",
    "Selangor",
    "Terengganu"
  ],
  "MV" => [
    "Central",
    "Male",
    "North",
    "North Central",
    "South",
    "South Central",
    "Upper North",
    "Upper South"
  ],
  "ML" => [
    "Bamako",
    "Gao",
    "Kayes",
    "Kidal",
    "Koulikoro",
    "Mopti",
    "Sikasso",
    "Ségou",
    "Tombouctou"
  ],
  "MT" => [
    "Attard",
    "Balzan",
    "Birgu",
    "Birkirkara",
    "Birżebbuġa",
    "Bormla",
    "Dingli",
    "Fgura",
    "Floriana",
    "Fontana",
    "Gudja",
    "Għajnsielem",
    "Għarb",
    "Għargħur",
    "Għasri",
    "Għaxaq",
    "Gżira",
    "Iklin",
    "Isla",
    "Kalkara",
    "Kerċem",
    "Kirkop",
    "Lija",
    "Luqa",
    "Marsa",
    "Marsaskala",
    "Marsaxlokk",
    "Mdina",
    "Mellieħa",
    "Mosta",
    "Mqabba",
    "Msida",
    "Mtarfa",
    "Munxar",
    "Mġarr",
    "Nadur",
    "Naxxar",
    "Paola",
    "Pembroke",
    "Pietà",
    "Qala",
    "Qormi",
    "Qrendi",
    "Rabat Għawdex",
    "Rabat Malta",
    "Safi",
    "San Lawrenz",
    "San Pawl il-Baħar",
    "San Ġiljan",
    "San Ġwann",
    "Sannat",
    "Santa Luċija",
    "Santa Venera",
    "Siġġiewi",
    "Sliema",
    "Swieqi",
    "Ta' Xbiex",
    "Tarxien",
    "Valletta",
    "Xagħra",
    "Xewkija",
    "Xgħajra",
    "Ħamrun",
    "Żabbar",
    "Żebbuġ Għawdex",
    "Żebbuġ Malta",
    "Żejtun",
    "Żurrieq"
  ],
  "MH" => [
    "Ralik chain",
    "Ratak chain"
  ],
  "MQ" => [
    "N/A"
  ],
  "MR" => [
    "Adrar",
    "Assaba",
    "Brakna",
    "Dakhlet Nouâdhibou",
    "Gorgol",
    "Guidimaka",
    "Hodh ech Chargui",
    "Hodh el Gharbi",
    "Inchiri",
    "Nouakchott",
    "Tagant",
    "Tiris Zemmour",
    "Trarza"
  ],
  "MU" => [
    "Agalega Islands",
    "Beau Bassin-Rose Hill",
    "Black River",
    "Cargados Carajos Shoals",
    "Curepipe",
    "Flacq",
    "Grand Port",
    "Moka",
    "Pamplemousses",
    "Plaines Wilhems",
    "Port Louis",
    "Port Louis",
    "Quatre Bornes",
    "Rivière du Rempart",
    "Rodrigues Island",
    "Savanne",
    "Vacoas-Phoenix"
  ],
  "YT" => [
    "N/A"
  ],
  "MX" => [
    "Distrito Federal",
    "Aguascalientes",
    "Baja California",
    "Baja California Sur",
    "Campeche",
    "Chiapas",
    "Chihuahua",
    "Coahuila",
    "Colima",
    "Durango",
    "Guanajuato",
    "Guerrero",
    "Hidalgo",
    "Jalisco",
    "Michoacán",
    "Morelos",
    "México",
    "Nayarit",
    "Nuevo León",
    "Oaxaca",
    "Puebla",
    "Querétaro",
    "Quintana Roo",
    "San Luis Potosí",
    "Sinaloa",
    "Sonora",
    "Tabasco",
    "Tamaulipas",
    "Tlaxcala",
    "Veracruz",
    "Yucatán",
    "Zacatecas"
  ],
  "FM" => [
    "Chuuk",
    "Kosrae",
    "Pohnpei",
    "Yap"
  ],
  "MD" => [
    "Anenii Noi",
    "Basarabeasca",
    "Briceni",
    "Bălţi",
    "Cahul",
    "Cantemir",
    "Chişinău",
    "Cimişlia",
    "Criuleni",
    "Călăraşi",
    "Căuşeni",
    "Donduşeni",
    "Drochia",
    "Dubăsari",
    "Edineţ",
    "Floreşti",
    "Făleşti",
    "Glodeni",
    "Găgăuzia, Unitatea teritorială autonomă",
    "Hînceşti",
    "Ialoveni",
    "Leova",
    "Nisporeni",
    "Ocniţa",
    "Orhei",
    "Rezina",
    "Rîşcani",
    "Soroca",
    "Străşeni",
    "Stînga Nistrului, unitatea teritorială din",
    "Sîngerei",
    "Taraclia",
    "Teleneşti",
    "Tighina",
    "Ungheni",
    "Şoldăneşti",
    "Ştefan Vodă"
  ],
  "MC" => [
    "Fontvieille",
    "Jardin Exotique",
    "La Colle",
    "La Condamine",
    "La Gare",
    "La Source",
    "Larvotto",
    "Malbousquet",
    "Monaco-Ville",
    "Moneghetti",
    "Monte-Carlo",
    "Moulins",
    "Port-Hercule",
    "Saint-Roman",
    "Sainte-Dévote",
    "Spélugues",
    "Vallon de la Rousse"
  ],
  "MN" => [
    "Arhangay",
    "Bayan-Ölgiy",
    "Bayanhongor",
    "Bulgan",
    "Darhan uul",
    "Dornod",
    "Dornogovĭ",
    "Dundgovĭ",
    "Dzavhan",
    "Govĭ-Altay",
    "Govĭ-Sümber",
    "Hentiy",
    "Hovd",
    "Hövsgöl",
    "Orhon",
    "Selenge",
    "Sühbaatar",
    "Töv",
    "Ulaanbaatar",
    "Uvs",
    "Ömnögovĭ",
    "Övörhangay"
  ],
  "ME" => [
    "Andrijevica",
    "Bar",
    "Berane",
    "Bijelo Polje",
    "Budva",
    "Cetinje",
    "Danilovgrad",
    "Gusinje",
    "Herceg-Novi",
    "Kolašin",
    "Kotor",
    "Mojkovac",
    "Nikšić",
    "Petnjica",
    "Plav",
    "Pljevlja",
    "Plužine",
    "Podgorica",
    "Rožaje",
    "Tivat",
    "Ulcinj",
    "Šavnik",
    "Žabljak"
  ],
  "MS" => [
    "N/A"
  ],
  "MA" => [
    "Chaouia-Ouardigha",
    "Doukhala-Abda",
    "Fès-Boulemane",
    "Gharb-Chrarda-Beni Hssen",
    "Grand Casablanca",
    "Guelmim-Es Smara",
    "L'Oriental",
    "Laâyoune-Boujdour-Sakia el Hamra",
    "Marrakech-Tensift-Al Haouz",
    "Meknès-Tafilalet",
    "Oued ed Dahab-Lagouira",
    "Rabat-Salé-Zemmour-Zaer",
    "Souss-Massa-Drâa",
    "Tadla-Azilal",
    "Tanger-Tétouan",
    "Taza-Al Hoceima-Taounate"
  ],
  "MZ" => [
    "Cabo Delgado",
    "Gaza",
    "Inhambane",
    "Manica",
    "Maputo",
    "Maputo",
    "Nampula",
    "Niassa",
    "Sofala",
    "Tete",
    "Zambézia"
  ],
  "MM" => [
    "Ayeyarwady",
    "Bago",
    "Chin",
    "Kachin",
    "Kayah",
    "Kayin",
    "Magway",
    "Mandalay",
    "Mon",
    "Rakhine",
    "Sagaing",
    "Shan",
    "Tanintharyi",
    "Yangon"
  ],
  "NA" => [
    "Erongo",
    "Hardap",
    "Karas",
    "Kavango East",
    "Kavango West",
    "Khomas",
    "Kunene",
    "Ohangwena",
    "Omaheke",
    "Omusati",
    "Oshana",
    "Oshikoto",
    "Otjozondjupa",
    "Zambezi"
  ],
  "NR" => [
    "Aiwo",
    "Anabar",
    "Anetan",
    "Anibare",
    "Baiti",
    "Boe",
    "Buada",
    "Denigomodu",
    "Ewa",
    "Ijuw",
    "Meneng",
    "Nibok",
    "Uaboe",
    "Yaren"
  ],
  "NP" => [
    "Madhya Pashchimanchal",
    "Madhyamanchal",
    "Pashchimanchal",
    "Purwanchal",
    "Sudur Pashchimanchal"
  ],
  "NL" => [
    "Drenthe",
    "Flevoland",
    "Fryslân",
    "Gelderland",
    "Groningen",
    "Limburg",
    "Noord-Brabant",
    "Noord-Holland",
    "Overijssel",
    "Utrecht",
    "Zeeland",
    "Zuid-Holland",
    "Aruba",
    "Curaçao",
    "Sint Maarten",
    "Bonaire",
    "Saba",
    "Sint Eustatius"
  ],
  "NC" => [
    "N/A"
  ],
  "NZ" => [
    "North Island",
    "South Island",
    "Auckland",
    "Bay of Plenty",
    "Canterbury",
    "Hawke's Bay",
    "Manawatu-Wanganui",
    "Northland",
    "Otago",
    "Southland",
    "Taranaki",
    "Waikato",
    "Wellington",
    "West Coast",
    "Chatham Islands Territory",
    "Gisborne District",
    "Marlborough District",
    "Nelson City",
    "Tasman District"
  ],
  "NI" => [
    "Atlántico Norte",
    "Atlántico Sur",
    "Boaco",
    "Carazo",
    "Chinandega",
    "Chontales",
    "Estelí",
    "Granada",
    "Jinotega",
    "León",
    "Madriz",
    "Managua",
    "Masaya",
    "Matagalpa",
    "Nueva Segovia",
    "Rivas",
    "Río San Juan"
  ],
  "NE" => [
    "Agadez",
    "Diffa",
    "Dosso",
    "Maradi",
    "Niamey",
    "Tahoua",
    "Tillabéri",
    "Zinder"
  ],
  "NG" => [
    "Abia",
    "Abuja Federal Capital Territory",
    "Adamawa",
    "Akwa Ibom",
    "Anambra",
    "Bauchi",
    "Bayelsa",
    "Benue",
    "Borno",
    "Cross River",
    "Delta",
    "Ebonyi",
    "Edo",
    "Ekiti",
    "Enugu",
    "Gombe",
    "Imo",
    "Jigawa",
    "Kaduna",
    "Kano",
    "Katsina",
    "Kebbi",
    "Kogi",
    "Kwara",
    "Lagos",
    "Nassarawa",
    "Niger",
    "Ogun",
    "Ondo",
    "Osun",
    "Oyo",
    "Plateau",
    "Rivers",
    "Sokoto",
    "Taraba",
    "Yobe",
    "Zamfara"
  ],
  "NU" => [
    "N/A"
  ],
  "NF" => [
    "N/A"
  ],
  "KP" => [
    "Chagang",
    "Kangwon",
    "North Hamgyong",
    "North Hwanghae",
    "North Pyongan",
    "Pyongyang",
    "Rason",
    "Ryanggang",
    "South Hamgyong",
    "South Hwanghae",
    "South Pyongan"
  ],
  "MP" => [
    "N/A"
  ],
  "NO" => [
    "Akershus",
    "Aust-Agder",
    "Buskerud",
    "Finnmark",
    "Hedmark",
    "Hordaland",
    "Jan Mayen",
    "Møre og Romsdal",
    "Nord-Trøndelag",
    "Nordland",
    "Oppland",
    "Oslo",
    "Rogaland",
    "Sogn og Fjordane",
    "Svalbard",
    "Sør-Trøndelag",
    "Telemark",
    "Troms",
    "Vest-Agder",
    "Vestfold",
    "Østfold"
  ],
  "OM" => [
    "Ad Dākhilīyah",
    "Al Buraymī",
    "Al Bāţinah",
    "Al Wusţá",
    "Ash Sharqīyah",
    "Az̧ Z̧āhirah",
    "Masqaţ",
    "Musandam",
    "Z̧ufār"
  ],
  "PK" => [
    "Azad Kashmir",
    "Balochistan",
    "Federally Administered Tribal Areas",
    "Gilgit-Baltistan",
    "Islamabad",
    "Khyber Pakhtunkhwa",
    "Punjab",
    "Sindh"
  ],
  "PW" => [
    "Aimeliik",
    "Airai",
    "Angaur",
    "Hatobohei",
    "Kayangel",
    "Koror",
    "Melekeok",
    "Ngaraard",
    "Ngarchelong",
    "Ngardmau",
    "Ngatpang",
    "Ngchesar",
    "Ngeremlengui",
    "Ngiwal",
    "Peleliu",
    "Sonsorol"
  ],
  "PS" => [
    "Bethlehem",
    "Deir El Balah",
    "Gaza",
    "Hebron",
    "Jenin",
    "Jericho - Al Aghwar",
    "Jerusalem",
    "Khan Yunis",
    "Nablus",
    "North Gaza",
    "Qalqilya",
    "Rafah",
    "Ramallah",
    "Salfit",
    "Tubas",
    "Tulkarm"
  ],
  "PA" => [
    "Bocas del Toro",
    "Chiriquí",
    "Coclé",
    "Colón",
    "Darién",
    "Emberá",
    "Herrera",
    "Kuna Yala",
    "Los Santos",
    "Ngöbe-Buglé",
    "Panamá",
    "Panamá Oeste",
    "Veraguas"
  ],
  "PG" => [
    "Bougainville",
    "Central",
    "Chimbu",
    "East New Britain",
    "East Sepik",
    "Eastern Highlands",
    "Enga",
    "Gulf",
    "Madang",
    "Manus",
    "Milne Bay",
    "Morobe",
    "National Capital District",
    "New Ireland",
    "Northern",
    "Sandaun",
    "Southern Highlands",
    "West New Britain",
    "Western",
    "Western Highlands"
  ],
  "PY" => [
    "Alto Paraguay",
    "Alto Paraná",
    "Amambay",
    "Asunción",
    "Boquerón",
    "Caaguazú",
    "Caazapá",
    "Canindeyú",
    "Central",
    "Concepción",
    "Cordillera",
    "Guairá",
    "Itapúa",
    "Misiones",
    "Paraguarí",
    "Presidente Hayes",
    "San Pedro",
    "Ñeembucú"
  ],
  "PE" => [
    "Amazonas",
    "Ancash",
    "Apurímac",
    "Arequipa",
    "Ayacucho",
    "Cajamarca",
    "Cusco",
    "El Callao",
    "Huancavelica",
    "Huánuco",
    "Ica",
    "Junín",
    "La Libertad",
    "Lambayeque",
    "Lima",
    "Loreto",
    "Madre de Dios",
    "Moquegua",
    "Municipalidad Metropolitana de Lima",
    "Pasco",
    "Piura",
    "Puno",
    "San Martín",
    "Tacna",
    "Tumbes",
    "Ucayali"
  ],
  "PH" => [
    "Autonomous Region in Muslim Mindanao",
    "Bicol",
    "Cagayan Valley",
    "Calabarzon",
    "Caraga",
    "Central Luzon",
    "Central Visayas",
    "Cordillera Administrative Region",
    "Davao",
    "Eastern Visayas",
    "Ilocos",
    "Mimaropa",
    "National Capital Region",
    "Northern Mindanao",
    "Soccsksargen",
    "Western Visayas",
    "Zamboanga Peninsula"
  ],
  "PN" => [
    "N/A"
  ],
  "PL" => [
    "Dolnośląskie",
    "Kujawsko-pomorskie",
    "Lubelskie",
    "Lubuskie",
    "Mazowieckie",
    "Małopolskie",
    "Opolskie",
    "Podkarpackie",
    "Podlaskie",
    "Pomorskie",
    "Warmińsko-mazurskie",
    "Wielkopolskie",
    "Zachodniopomorskie",
    "Łódzkie",
    "Śląskie",
    "Świętokrzyskie"
  ],
  "PT" => [
    "Aveiro",
    "Beja",
    "Braga",
    "Bragança",
    "Castelo Branco",
    "Coimbra",
    "Faro",
    "Guarda",
    "Leiria",
    "Lisboa",
    "Portalegre",
    "Porto",
    "Região Autónoma da Madeira",
    "Região Autónoma dos Açores",
    "Santarém",
    "Setúbal",
    "Viana do Castelo",
    "Vila Real",
    "Viseu",
    "Évora"
  ],
  "PR" => [
    "N/A"
  ],
  "QA" => [
    "Ad Dawḩah",
    "Al Khawr wa adh Dhakhīrah",
    "Al Wakrah",
    "Ar Rayyān",
    "Ash Shamāl",
    "Az̧ Za̧`āyin",
    "Umm Şalāl"
  ],
  "XK" => [
    "N/A"
  ],
  "RE" => [
    "N/A"
  ],
  "RO" => [
    "Alba",
    "Arad",
    "Argeș",
    "Bacău",
    "Bihor",
    "Bistrița-Năsăud",
    "Botoșani",
    "Brașov",
    "Brăila",
    "București",
    "Buzău",
    "Caraș-Severin",
    "Cluj",
    "Constanța",
    "Covasna",
    "Călărași",
    "Dolj",
    "Dâmbovița",
    "Galați",
    "Giurgiu",
    "Gorj",
    "Harghita",
    "Hunedoara",
    "Ialomița",
    "Iași",
    "Ilfov",
    "Maramureș",
    "Mehedinți",
    "Mureș",
    "Neamț",
    "Olt",
    "Prahova",
    "Satu Mare",
    "Sibiu",
    "Suceava",
    "Sălaj",
    "Teleorman",
    "Timiș",
    "Tulcea",
    "Vaslui",
    "Vrancea",
    "Vâlcea"
  ],
  "RU" => [
    "Amurskaya oblast'",
    "Arkhangel'skaya oblast'",
    "Astrakhanskaya oblast'",
    "Belgorodskaya oblast'",
    "Bryanskaya oblast'",
    "Chelyabinskaya oblast'",
    "Irkutskaya oblast'",
    "Ivanovskaya oblast'",
    "Kaliningradskaya oblast'",
    "Kaluzhskaya oblast'",
    "Kemerovskaya oblast'",
    "Kirovskaya oblast'",
    "Kostromskaya oblast'",
    "Kurganskaya oblast'",
    "Kurskaya oblast'",
    "Leningradskaya oblast'",
    "Lipetskaya oblast'",
    "Magadanskaya oblast'",
    "Moskovskaya oblast'",
    "Murmanskaya oblast'",
    "Nizhegorodskaya oblast'",
    "Novgorodskaya oblast'",
    "Novosibirskaya oblast'",
    "Omskaya oblast'",
    "Orenburgskaya oblast'",
    "Orlovskaya oblast'",
    "Penzenskaya oblast'",
    "Pskovskaya oblast'",
    "Rostovskaya oblast'",
    "Ryazanskaya oblast'",
    "Sakhalinskaya oblast'",
    "Samarskaya oblast'",
    "Saratovskaya oblast'",
    "Smolenskaya oblast'",
    "Sverdlovskaya oblast'",
    "Tambovskaya oblast'",
    "Tomskaya oblast'",
    "Tul'skaya oblast'",
    "Tverskaya oblast'",
    "Tyumenskaya oblast'",
    "Ul'yanovskaya oblast'",
    "Vladimirskaya oblast'",
    "Volgogradskaya oblast'",
    "Vologodskaya oblast'",
    "Voronezhskaya oblast'",
    "Yaroslavskaya oblast'",
    "Altayskiy kray",
    "Kamchatskiy kray",
    "Khabarovskiy kray",
    "Krasnodarskiy kray",
    "Krasnoyarskiy kray",
    "Permskiy kray",
    "Primorskiy kray",
    "Stavropol'skiy kray",
    "Zabaykal'skiy kray",
    "Moskva",
    "Sankt-Peterburg",
    "Chukotskiy avtonomnyy okrug",
    "Khanty-Mansiyskiy avtonomnyy okrug-Yugra",
    "Nenetskiy avtonomnyy okrug",
    "Yamalo-Nenetskiy avtonomnyy okrug",
    "Yevreyskaya avtonomnaya oblast'",
    "Adygeya, Respublika",
    "Altay, Respublika",
    "Bashkortostan, Respublika",
    "Buryatiya, Respublika",
    "Chechenskaya Respublika",
    "Chuvashskaya Respublika",
    "Dagestan, Respublika",
    "Ingushetiya, Respublika",
    "Kabardino-Balkarskaya Respublika",
    "Kalmykiya, Respublika",
    "Karachayevo-Cherkesskaya Respublika",
    "Kareliya, Respublika",
    "Khakasiya, Respublika",
    "Komi, Respublika",
    "Mariy El, Respublika",
    "Mordoviya, Respublika",
    "Sakha, Respublika",
    "Severnaya Osetiya-Alaniya, Respublika",
    "Tatarstan, Respublika",
    "Tyva, Respublika",
    "Udmurtskaya Respublika"
  ],
  "RW" => [
    "Est",
    "Nord",
    "Ouest",
    "Sud",
    "Ville de Kigali"
  ],
  "BL" => [
    "N/A"
  ],
  "SH" => [
    "Ascension",
    "Saint Helena",
    "Tristan da Cunha"
  ],
  "KN" => [
    "Nevis",
    "Saint Kitts"
  ],
  "LC" => [
    "Anse la Raye",
    "Castries",
    "Choiseul",
    "Dauphin",
    "Dennery",
    "Gros Islet",
    "Laborie",
    "Micoud",
    "Praslin",
    "Soufrière",
    "Vieux Fort"
  ],
  "MF" => [
    "N/A"
  ],
  "PM" => [
    "N/A"
  ],
  "VC" => [
    "Charlotte",
    "Grenadines",
    "Saint Andrew",
    "Saint David",
    "Saint George",
    "Saint Patrick"
  ],
  "WS" => [
    "A'ana",
    "Aiga-i-le-Tai",
    "Atua",
    "Fa'asaleleaga",
    "Gaga'emauga",
    "Gagaifomauga",
    "Palauli",
    "Satupa'itea",
    "Tuamasaga",
    "Va'a-o-Fonoti",
    "Vaisigano"
  ],
  "SM" => [
    "Acquaviva",
    "Borgo Maggiore",
    "Chiesanuova",
    "Domagnano",
    "Faetano",
    "Fiorentino",
    "Montegiardino",
    "San Marino",
    "Serravalle"
  ],
  "ST" => [
    "Príncipe",
    "São Tomé"
  ],
  "SA" => [
    "Al Bāḩah",
    "Al Jawf",
    "Al Madīnah",
    "Al Qaşīm",
    "Al Ḩudūd ash Shamālīyah",
    "Ar Riyāḑ",
    "Ash Sharqīyah",
    "Jīzān",
    "Makkah",
    "Najrān",
    "Tabūk",
    "ٰĀsīr",
    "Ḩā'il"
  ],
  "SN" => [
    "Dakar",
    "Diourbel",
    "Fatick",
    "Kaffrine",
    "Kaolack",
    "Kolda",
    "Kédougou",
    "Louga",
    "Matam",
    "Saint-Louis",
    "Sédhiou",
    "Tambacounda",
    "Thiès",
    "Ziguinchor"
  ],
  "RS" => [
    "Kosovo-Metohija",
    "Vojvodina"
  ],
  "SC" => [
    "Anse Boileau",
    "Anse Etoile",
    "Anse Royale",
    "Anse aux Pins",
    "Au Cap",
    "Baie Lazare",
    "Baie Sainte Anne",
    "Beau Vallon",
    "Bel Air",
    "Bel Ombre",
    "Cascade",
    "English River",
    "Glacis",
    "Grand Anse Mahe",
    "Grand Anse Praslin",
    "La Digue",
    "Les Mamelles",
    "Mont Buxton",
    "Mont Fleuri",
    "Plaisance",
    "Pointe Larue",
    "Port Glaud",
    "Roche Caiman",
    "Saint Louis",
    "Takamaka"
  ],
  "SL" => [
    "Eastern",
    "Northern",
    "Southern",
    "Western Area"
  ],
  "SG" => [
    "Central Singapore",
    "North East",
    "North West",
    "South East",
    "South West"
  ],
  "SX" => [
    "N/A"
  ],
  "SK" => [
    "Banskobystrický kraj",
    "Bratislavský kraj",
    "Košický kraj",
    "Nitriansky kraj",
    "Prešovský kraj",
    "Trenčiansky kraj",
    "Trnavský kraj",
    "Žilinský kraj"
  ],
  "SI" => [
    "Ajdovščina",
    "Apače",
    "Beltinci",
    "Benedikt",
    "Bistrica ob Sotli",
    "Bled",
    "Bloke",
    "Bohinj",
    "Borovnica",
    "Bovec",
    "Braslovče",
    "Brda",
    "Brezovica",
    "Brežice",
    "Cankova",
    "Celje",
    "Cerklje na Gorenjskem",
    "Cerknica",
    "Cerkno",
    "Cerkvenjak",
    "Cirkulane",
    "Destrnik",
    "Divača",
    "Dobje",
    "Dobrepolje",
    "Dobrna",
    "Dobrova-Polhov Gradec",
    "Dobrovnik",
    "Dol pri Ljubljani",
    "Dolenjske Toplice",
    "Domžale",
    "Dornava",
    "Dravograd",
    "Duplek",
    "Gorenja vas-Poljane",
    "Gorišnica",
    "Gorje",
    "Gornja Radgona",
    "Gornji Grad",
    "Gornji Petrovci",
    "Grad",
    "Grosuplje",
    "Hajdina",
    "Hodoš",
    "Horjul",
    "Hoče-Slivnica",
    "Hrastnik",
    "Hrpelje-Kozina",
    "Idrija",
    "Ig",
    "Ilirska Bistrica",
    "Ivančna Gorica",
    "Izola",
    "Jesenice",
    "Jezersko",
    "Juršinci",
    "Kamnik",
    "Kanal",
    "Kidričevo",
    "Kobarid",
    "Kobilje",
    "Komen",
    "Komenda",
    "Koper",
    "Kosanjevica na Krki",
    "Kostel",
    "Kozje",
    "Kočevje",
    "Kranj",
    "Kranjska Gora",
    "Križevci",
    "Krško",
    "Kungota",
    "Kuzma",
    "Laško",
    "Lenart",
    "Lendava",
    "Litija",
    "Ljubljana",
    "Ljubno",
    "Ljutomer",
    "Log-Dragomer",
    "Logatec",
    "Lovrenc na Pohorju",
    "Loška Dolina",
    "Loški Potok",
    "Lukovica",
    "Luče",
    "Majšperk",
    "Makole",
    "Maribor",
    "Markovci",
    "Medvode",
    "Mengeš",
    "Metlika",
    "Mežica",
    "Miklavž na Dravskem Polju",
    "Miren-Kostanjevica",
    "Mirna Peč",
    "Mislinja",
    "Mokronog-Trebelno",
    "Moravske Toplice",
    "Moravče",
    "Mozirje",
    "Murska Sobota",
    "Muta",
    "Naklo",
    "Nazarje",
    "Nova Gorica",
    "Novo Mesto",
    "Odranci",
    "Oplotnica",
    "Ormož",
    "Osilnica",
    "Pesnica",
    "Piran",
    "Pivka",
    "Podlehnik",
    "Podvelka",
    "Podčetrtek",
    "Poljčane",
    "Polzela",
    "Postojna",
    "Prebold",
    "Preddvor",
    "Prevalje",
    "Ptuj",
    "Puconci",
    "Radenci",
    "Radeče",
    "Radlje ob Dravi",
    "Radovljica",
    "Ravne na Koroškem",
    "Razkrižje",
    "Rače-Fram",
    "Renče-Vogrsko",
    "Rečica ob Savinji",
    "Ribnica",
    "Ribnica na Pohorju",
    "Rogatec",
    "Rogaška Slatina",
    "Rogašovci",
    "Ruše",
    "Selnica ob Dravi",
    "Semič",
    "Sevnica",
    "Sežana",
    "Slovenj Gradec",
    "Slovenska Bistrica",
    "Slovenske Konjice",
    "Sodražica",
    "Solčava",
    "Središče ob Dravi",
    "Starše",
    "Straža",
    "Sveta Ana",
    "Sveta Trojica v Slovenskih Goricah",
    "Sveti Andraž v Slovenskih Goricah",
    "Sveti Jurij",
    "Sveti Jurij v Slovenskih Goricah",
    "Sveti Tomaž",
    "Tabor",
    "Tišina",
    "Tolmin",
    "Trbovlje",
    "Trebnje",
    "Trnovska Vas",
    "Trzin",
    "Tržič",
    "Turnišče",
    "Velenje",
    "Velika Polana",
    "Velike Lašče",
    "Veržej",
    "Videm",
    "Vipava",
    "Vitanje",
    "Vodice",
    "Vojnik",
    "Vransko",
    "Vrhnika",
    "Vuzenica",
    "Zagorje ob Savi",
    "Zavrč",
    "Zreče",
    "Črenšovci",
    "Črna na Koroškem",
    "Črnomelj",
    "Šalovci",
    "Šempeter-Vrtojba",
    "Šentilj",
    "Šentjernej",
    "Šentjur",
    "Šentrupert",
    "Šenčur",
    "Škocjan",
    "Škofja Loka",
    "Škofljica",
    "Šmarje pri Jelšah",
    "Šmarješke Toplice",
    "Šmartno ob Paki",
    "Šmartno pri Litiji",
    "Šoštanj",
    "Štore",
    "Žalec",
    "Železniki",
    "Žetale",
    "Žiri",
    "Žirovnica",
    "Žužemberk"
  ],
  "SB" => [
    "Capital Territory",
    "Central",
    "Choiseul",
    "Guadalcanal",
    "Isabel",
    "Makira-Ulawa",
    "Malaita",
    "Rennell and Bellona",
    "Temotu",
    "Western"
  ],
  "SO" => [
    "Awdal",
    "Bakool",
    "Banaadir",
    "Bari",
    "Bay",
    "Galguduud",
    "Gedo",
    "Hiiraan",
    "Jubbada Dhexe",
    "Jubbada Hoose",
    "Mudug",
    "Nugaal",
    "Sanaag",
    "Shabeellaha Dhexe",
    "Shabeellaha Hoose",
    "Sool",
    "Togdheer",
    "Woqooyi Galbeed"
  ],
  "ZA" => [
    "Eastern Cape",
    "Free State",
    "Gauteng",
    "KwaZulu-Natal",
    "Limpopo",
    "Mpumalanga",
    "North West",
    "Northern Cape",
    "Western Cape"
  ],
  "GS" => [
    "N/A"
  ],
  "KR" => [
    "Busan-gwangyeoksi",
    "Chungcheongbuk-do",
    "Chungcheongnam-do",
    "Daegu-gwangyeoksi",
    "Daejeon-gwangyeoksi",
    "Gangwon-do",
    "Gwangju-gwangyeoksi",
    "Gyeonggi-do",
    "Gyeongsangbuk-do",
    "Gyeongsangnam-do",
    "Incheon-gwangyeoksi",
    "Jeju-teukbyeoljachido",
    "Jeollabuk-do",
    "Jeollanam-do",
    "Sejong",
    "Seoul-teukbyeolsi",
    "Ulsan-gwangyeoksi"
  ],
  "SS" => [
    "Central Equatoria",
    "Eastern Equatoria",
    "Jonglei",
    "Lakes",
    "Northern Bahr el Ghazal",
    "Unity",
    "Upper Nile",
    "Warrap",
    "Western Bahr el Ghazal",
    "Western Equatoria"
  ],
  "ES" => [
    "A Coruña",
    "Albacete",
    "Alicante",
    "Almería",
    "Asturias",
    "Badajoz",
    "Balears",
    "Barcelona",
    "Burgos",
    "Cantabria",
    "Castellón",
    "Ciudad Real",
    "Cuenca",
    "Cáceres",
    "Cádiz",
    "Córdoba",
    "Girona",
    "Granada",
    "Guadalajara",
    "Guipúzcoa",
    "Huelva",
    "Huesca",
    "Jaén",
    "La Rioja",
    "Las Palmas",
    "León",
    "Lleida",
    "Lugo",
    "Madrid",
    "Murcia",
    "Málaga",
    "Navarra",
    "Ourense",
    "Palencia",
    "Pontevedra",
    "Salamanca",
    "Santa Cruz de Tenerife",
    "Segovia",
    "Sevilla",
    "Soria",
    "Tarragona",
    "Teruel",
    "Toledo",
    "Valencia",
    "Valladolid",
    "Vizcaya",
    "Zamora",
    "Zaragoza",
    "Álava",
    "Ávila",
    "Ceuta",
    "Melilla",
    "Andalucía",
    "Aragón",
    "Asturias, Principado de",
    "Canarias",
    "Cantabria",
    "Castilla y León",
    "Castilla-La Mancha",
    "Catalunya",
    "Extremadura",
    "Galicia",
    "Illes Balears",
    "La Rioja",
    "Madrid, Comunidad de",
    "Murcia, Región de",
    "Navarra, Comunidad Foral de",
    "País Vasco",
    "Valenciana, Comunidad"
  ],
  "LK" => [
    "Central Province",
    "Eastern Province",
    "North Central Province",
    "North Western Province",
    "Northern Province",
    "Sabaragamuwa Province",
    "Southern Province",
    "Uva Province",
    "Western Province"
  ],
  "SD" => [
    "Al Baḩr al Aḩmar",
    "Al Jazīrah",
    "Al Kharţūm",
    "Al Qaḑārif",
    "An Nīl",
    "An Nīl al Abyaḑ",
    "An Nīl al Azraq",
    "Ash Shamālīyah",
    "Gharb Dārfūr",
    "Janūb Dārfūr",
    "Janūb Kurdufān",
    "Kassalā",
    "Shamāl Dārfūr",
    "Shamāl Kurdufān",
    "Sharq Dārfūr",
    "Sinnār",
    "Zalingei"
  ],
  "SR" => [
    "Brokopondo",
    "Commewijne",
    "Coronie",
    "Marowijne",
    "Nickerie",
    "Para",
    "Paramaribo",
    "Saramacca",
    "Sipaliwini",
    "Wanica"
  ],
  "SJ" => [
    "N/A"
  ],
  "SZ" => [
    "Hhohho",
    "Lubombo",
    "Manzini",
    "Shiselweni"
  ],
  "SE" => [
    "Blekinge län",
    "Dalarnas län",
    "Gotlands län",
    "Gävleborgs län",
    "Hallands län",
    "Jämtlands län",
    "Jönköpings län",
    "Kalmar län",
    "Kronobergs län",
    "Norrbottens län",
    "Skåne län",
    "Stockholms län",
    "Södermanlands län",
    "Uppsala län",
    "Värmlands län",
    "Västerbottens län",
    "Västernorrlands län",
    "Västmanlands län",
    "Västra Götalands län",
    "Örebro län",
    "Östergötlands län"
  ],
  "CH" => [
    "Aargau",
    "Appenzell Ausserrhoden",
    "Appenzell Innerrhoden",
    "Basel-Landschaft",
    "Basel-Stadt",
    "Bern",
    "Fribourg",
    "Genève",
    "Glarus",
    "Graubünden",
    "Jura",
    "Luzern",
    "Neuchâtel",
    "Nidwalden",
    "Obwalden",
    "Sankt Gallen",
    "Schaffhausen",
    "Schwyz",
    "Solothurn",
    "Thurgau",
    "Ticino",
    "Uri",
    "Valais",
    "Vaud",
    "Zug",
    "Zürich"
  ],
  "SY" => [
    "Al Lādhiqīyah",
    "Al Qunayţirah",
    "Al Ḩasakah",
    "Ar Raqqah",
    "As Suwaydā'",
    "Darٰā",
    "Dayr az Zawr",
    "Dimashq",
    "Idlib",
    "Rīf Dimashq",
    "Ţarţūs",
    "Ḩalab",
    "Ḩamāh",
    "Ḩimş"
  ],
  "TW" => [
    "Changhua",
    "Chiayi",
    "Chiayi",
    "Hsinchu",
    "Hsinchu",
    "Hualien",
    "Ilan",
    "Kaohsiung",
    "Kaohsiung",
    "Keelung",
    "Miaoli",
    "Nantou",
    "Penghu",
    "Pingtung",
    "Taichung",
    "Taichung",
    "Tainan",
    "Tainan",
    "Taipei",
    "Taipei",
    "Taitung",
    "Taoyuan",
    "Yunlin"
  ],
  "TJ" => [
    "Dushanbe",
    "Khatlon",
    "Kŭhistoni Badakhshon",
    "Sughd"
  ],
  "TZ" => [
    "Arusha",
    "Dar es Salaam",
    "Dodoma",
    "Iringa",
    "Kagera",
    "Kaskazini Pemba",
    "Kaskazini Unguja",
    "Kigoma",
    "Kilimanjaro",
    "Kusini Pemba",
    "Kusini Unguja",
    "Lindi",
    "Manyara",
    "Mara",
    "Mbeya",
    "Mjini Magharibi",
    "Morogoro",
    "Mtwara",
    "Mwanza",
    "Pwani",
    "Rukwa",
    "Ruvuma",
    "Shinyanga",
    "Singida",
    "Tabora",
    "Tanga"
  ],
  "TH" => [
    "Amnat Charoen",
    "Ang Thong",
    "Bueng Kan",
    "Buri Ram",
    "Chachoengsao",
    "Chai Nat",
    "Chaiyaphum",
    "Chanthaburi",
    "Chiang Mai",
    "Chiang Rai",
    "Chon Buri",
    "Chumphon",
    "Kalasin",
    "Kamphaeng Phet",
    "Kanchanaburi",
    "Khon Kaen",
    "Krabi",
    "Krung Thep Maha Nakhon",
    "Lampang",
    "Lamphun",
    "Loei",
    "Lop Buri",
    "Mae Hong Son",
    "Maha Sarakham",
    "Mukdahan",
    "Nakhon Nayok",
    "Nakhon Pathom",
    "Nakhon Phanom",
    "Nakhon Ratchasima",
    "Nakhon Sawan",
    "Nakhon Si Thammarat",
    "Nan",
    "Narathiwat",
    "Nong Bua Lam Phu",
    "Nong Khai",
    "Nonthaburi",
    "Pathum Thani",
    "Pattani",
    "Phangnga",
    "Phatthalung",
    "Phatthaya",
    "Phayao",
    "Phetchabun",
    "Phetchaburi",
    "Phichit",
    "Phitsanulok",
    "Phra Nakhon Si Ayutthaya",
    "Phrae",
    "Phuket",
    "Prachin Buri",
    "Prachuap Khiri Khan",
    "Ranong",
    "Ratchaburi",
    "Rayong",
    "Roi Et",
    "Sa Kaeo",
    "Sakon Nakhon",
    "Samut Prakan",
    "Samut Sakhon",
    "Samut Songkhram",
    "Saraburi",
    "Satun",
    "Si Sa Ket",
    "Sing Buri",
    "Songkhla",
    "Sukhothai",
    "Suphan Buri",
    "Surat Thani",
    "Surin",
    "Tak",
    "Trang",
    "Trat",
    "Ubon Ratchathani",
    "Udon Thani",
    "Uthai Thani",
    "Uttaradit",
    "Yala",
    "Yasothon"
  ],
  "TL" => [
    "Aileu",
    "Ainaro",
    "Baucau",
    "Bobonaro",
    "Cova Lima",
    "Díli",
    "Ermera",
    "Lautem",
    "Liquiça",
    "Manatuto",
    "Manufahi",
    "Oecussi",
    "Viqueque"
  ],
  "TG" => [
    "Centre",
    "Kara",
    "Maritime",
    "Plateaux",
    "Savannes"
  ],
  "TK" => [
    "N/A"
  ],
  "TO" => [
    "'Eua",
    "Ha'apai",
    "Niuas",
    "Tongatapu",
    "Vava'u"
  ],
  "TT" => [
    "Arima",
    "Chaguanas",
    "Couva-Tabaquite-Talparo",
    "Diego Martin",
    "Eastern Tobago",
    "Penal-Debe",
    "Point Fortin",
    "Port of Spain",
    "Princes Town",
    "Rio Claro-Mayaro",
    "San Fernando",
    "San Juan-Laventille",
    "Sangre Grande",
    "Siparia",
    "Tunapuna-Piarco",
    "Western Tobago"
  ],
  "TN" => [
    "Ariana",
    "Ben Arous",
    "Bizerte",
    "Béja",
    "Gabès",
    "Gafsa",
    "Jendouba",
    "Kairouan",
    "Kasserine",
    "Kebili",
    "La Manouba",
    "Le Kef",
    "Mahdia",
    "Medenine",
    "Monastir",
    "Nabeul",
    "Sfax",
    "Sidi Bouzid",
    "Siliana",
    "Sousse",
    "Tataouine",
    "Tozeur",
    "Tunis",
    "Zaghouan"
  ],
  "TR" => [
    "Adana",
    "Adiyaman",
    "Afyonkarahisar",
    "Aksaray",
    "Amasya",
    "Ankara",
    "Antalya",
    "Ardahan",
    "Artvin",
    "Aydin",
    "Ağri",
    "Balikesir",
    "Bartin",
    "Batman",
    "Bayburt",
    "Bilecik",
    "Bingöl",
    "Bitlis",
    "Bolu",
    "Burdur",
    "Bursa",
    "Denizli",
    "Diyarbakir",
    "Düzce",
    "Edirne",
    "Elaziğ",
    "Erzincan",
    "Erzurum",
    "Eskişehir",
    "Gaziantep",
    "Giresun",
    "Gümüşhane",
    "Hakkâri",
    "Hatay",
    "Isparta",
    "Iğdir",
    "Kahramanmaraş",
    "Karabük",
    "Karaman",
    "Kars",
    "Kastamonu",
    "Kayseri",
    "Kilis",
    "Kocaeli",
    "Konya",
    "Kütahya",
    "Kirklareli",
    "Kirikkale",
    "Kirşehir",
    "Malatya",
    "Manisa",
    "Mardin",
    "Mersin",
    "Muğla",
    "Muş",
    "Nevşehir",
    "Niğde",
    "Ordu",
    "Osmaniye",
    "Rize",
    "Sakarya",
    "Samsun",
    "Siirt",
    "Sinop",
    "Sivas",
    "Tekirdağ",
    "Tokat",
    "Trabzon",
    "Tunceli",
    "Uşak",
    "Van",
    "Yalova",
    "Yozgat",
    "Zonguldak",
    "Çanakkale",
    "Çankiri",
    "Çorum",
    "İstanbul",
    "İzmir",
    "Şanliurfa",
    "Şirnak"
  ],
  "TM" => [
    "Ahal",
    "Aşgabat",
    "Balkan",
    "Daşoguz",
    "Lebap",
    "Mary"
  ],
  "TC" => [
    "N/A"
  ],
  "TV" => [
    "Funafuti",
    "Nanumanga",
    "Nanumea",
    "Niutao",
    "Nui",
    "Nukufetau",
    "Nukulaelae",
    "Vaitupu"
  ],
  "UG" => [
    "Central",
    "Eastern",
    "Northern",
    "Western"
  ],
  "UA" => [
    "Avtonomna Respublika Krym",
    "Cherkas'ka Oblast'",
    "Chernihivs'ka Oblast'",
    "Chernivets'ka Oblast'",
    "Dnipropetrovs'ka Oblast'",
    "Donets'ka Oblast'",
    "Ivano-Frankivs'ka Oblast'",
    "Kharkivs'ka Oblast'",
    "Khersons'ka Oblast'",
    "Khmel'nyts'ka Oblast'",
    "Kirovohrads'ka Oblast'",
    "Kyïv",
    "Kyïvs'ka Oblast'",
    "L'vivs'ka Oblast'",
    "Luhans'ka Oblast'",
    "Mykolaïvs'ka Oblast'",
    "Odes'ka Oblast'",
    "Poltavs'ka Oblast'",
    "Rivnens'ka Oblast'",
    "Sevastopol'",
    "Sums'ka Oblast'",
    "Ternopil's'ka Oblast'",
    "Vinnyts'ka Oblast'",
    "Volyns'ka Oblast'",
    "Zakarpats'ka Oblast'",
    "Zaporiz'ka Oblast'",
    "Zhytomyrs'ka Oblast'"
  ],
  "AE" => [
    "'Ajmān",
    "Abū Z̧aby",
    "Al Fujayrah",
    "Ash Shāriqah",
    "Dubayy",
    "Ra's al Khaymah",
    "Umm al Qaywayn"
  ],
  "GB" => [
    "Barking and Dagenham",
    "Barnet",
    "Bexley",
    "Brent",
    "Bromley",
    "Camden",
    "Croydon",
    "Ealing",
    "Enfield",
    "Greenwich",
    "Hackney",
    "Hammersmith and Fulham",
    "Haringey",
    "Harrow",
    "Havering",
    "Hillingdon",
    "Hounslow",
    "Islington",
    "Kensington and Chelsea",
    "Kingston upon Thames",
    "Lambeth",
    "Lewisham",
    "Merton",
    "Newham",
    "Redbridge",
    "Richmond upon Thames",
    "Southwark",
    "Sutton",
    "Tower Hamlets",
    "Waltham Forest",
    "Wandsworth",
    "Westminster",
    "England and Wales",
    "Great Britain",
    "United Kingdom",
    "London, City of",
    "Aberdeen City",
    "Aberdeenshire",
    "Angus",
    "Argyll and Bute",
    "Clackmannanshire",
    "Dumfries and Galloway",
    "Dundee City",
    "East Ayrshire",
    "East Dunbartonshire",
    "East Lothian",
    "East Renfrewshire",
    "Edinburgh, City of",
    "Eilean Siar",
    "Falkirk",
    "Fife",
    "Glasgow City",
    "Highland",
    "Inverclyde",
    "Midlothian",
    "Moray",
    "North Ayrshire",
    "North Lanarkshire",
    "Orkney Islands",
    "Perth and Kinross",
    "Renfrewshire",
    "Scottish Borders, The",
    "Shetland Islands",
    "South Ayrshire",
    "South Lanarkshire",
    "Stirling",
    "West Dunbartonshire",
    "West Lothian",
    "England",
    "Scotland",
    "Wales",
    "Antrim",
    "Ards",
    "Armagh",
    "Ballymena",
    "Ballymoney",
    "Banbridge",
    "Belfast",
    "Carrickfergus",
    "Castlereagh",
    "Coleraine",
    "Cookstown",
    "Craigavon",
    "Derry",
    "Down",
    "Dungannon and South Tyrone",
    "Fermanagh",
    "Larne",
    "Limavady",
    "Lisburn",
    "Magherafelt",
    "Moyle",
    "Newry and Mourne District",
    "Newtownabbey",
    "North Down",
    "Omagh",
    "Strabane",
    "Barnsley",
    "Birmingham",
    "Bolton",
    "Bradford",
    "Bury",
    "Calderdale",
    "Coventry",
    "Doncaster",
    "Dudley",
    "Gateshead",
    "Kirklees",
    "Knowsley",
    "Leeds",
    "Liverpool",
    "Manchester",
    "Newcastle upon Tyne",
    "North Tyneside",
    "Oldham",
    "Rochdale",
    "Rotherham",
    "Salford",
    "Sandwell",
    "Sefton",
    "Sheffield",
    "Solihull",
    "South Tyneside",
    "St. Helens",
    "Stockport",
    "Sunderland",
    "Tameside",
    "Trafford",
    "Wakefield",
    "Walsall",
    "Wigan",
    "Wirral",
    "Wolverhampton",
    "Northern Ireland",
    "Buckinghamshire",
    "Cambridgeshire",
    "Cumbria",
    "Derbyshire",
    "Devon",
    "Dorset",
    "East Sussex",
    "Essex",
    "Gloucestershire",
    "Hampshire",
    "Hertfordshire",
    "Kent",
    "Lancashire",
    "Leicestershire",
    "Lincolnshire",
    "Norfolk",
    "North Yorkshire",
    "Northamptonshire",
    "Nottinghamshire",
    "Oxfordshire",
    "Somerset",
    "Staffordshire",
    "Suffolk",
    "Surrey",
    "Warwickshire",
    "West Sussex",
    "Worcestershire",
    "Bath and North East Somerset",
    "Bedford",
    "Blackburn with Darwen",
    "Blackpool",
    "Blaenau Gwent",
    "Bournemouth",
    "Bracknell Forest",
    "Bridgend",
    "Brighton and Hove",
    "Bristol, City of",
    "Caerphilly",
    "Cardiff",
    "Carmarthenshire",
    "Central Bedfordshire",
    "Ceredigion",
    "Cheshire East",
    "Cheshire West and Chester",
    "Conwy",
    "Cornwall",
    "Darlington",
    "Denbighshire",
    "Derby",
    "Durham, County",
    "East Riding of Yorkshire",
    "Flintshire",
    "Gwynedd",
    "Halton",
    "Hartlepool",
    "Herefordshire",
    "Isle of Anglesey",
    "Isle of Wight",
    "Isles of Scilly",
    "Kingston upon Hull",
    "Leicester",
    "Luton",
    "Medway",
    "Merthyr Tydfil",
    "Middlesbrough",
    "Milton Keynes",
    "Monmouthshire",
    "Neath Port Talbot",
    "Newport",
    "North East Lincolnshire",
    "North Lincolnshire",
    "North Somerset",
    "Northumberland",
    "Nottingham",
    "Pembrokeshire",
    "Peterborough",
    "Plymouth",
    "Poole",
    "Portsmouth",
    "Powys",
    "Reading",
    "Redcar and Cleveland",
    "Rhondda, Cynon, Taff",
    "Rutland",
    "Shropshire",
    "Slough",
    "South Gloucestershire",
    "Southampton",
    "Southend-on-Sea",
    "Stockton-on-Tees",
    "Stoke-on-Trent",
    "Swansea",
    "Swindon",
    "Telford and Wrekin",
    "Thurrock",
    "Torbay",
    "Torfaen",
    "Vale of Glamorgan, The",
    "Warrington",
    "West Berkshire",
    "Wiltshire",
    "Windsor and Maidenhead",
    "Wokingham",
    "Wrexham",
    "York"
  ],
  "US" => [
    "District of Columbia",
    "American Samoa",
    "Guam",
    "Northern Mariana Islands",
    "Puerto Rico",
    "United States Minor Outlying Islands",
    "Virgin Islands, U.S.",
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming"
  ],
  "UY" => [
    "Artigas",
    "Canelones",
    "Cerro Largo",
    "Colonia",
    "Durazno",
    "Flores",
    "Florida",
    "Lavalleja",
    "Maldonado",
    "Montevideo",
    "Paysandú",
    "Rivera",
    "Rocha",
    "Río Negro",
    "Salto",
    "San José",
    "Soriano",
    "Tacuarembó",
    "Treinta y Tres"
  ],
  "UZ" => [
    "Andijon",
    "Buxoro",
    "Farg'ona",
    "Jizzax",
    "Namangan",
    "Navoiy",
    "Qashqadaryo",
    "Qoraqalpog'iston Respublikasi",
    "Samarqand",
    "Sirdaryo",
    "Surxondaryo",
    "Toshkent",
    "Toshkent",
    "Xorazm"
  ],
  "VU" => [
    "Malampa",
    "Pénama",
    "Sanma",
    "Shéfa",
    "Taféa",
    "Torba"
  ],
  "VE" => [
    "Amazonas",
    "Anzoátegui",
    "Apure",
    "Aragua",
    "Barinas",
    "Bolívar",
    "Carabobo",
    "Cojedes",
    "Delta Amacuro",
    "Dependencias Federales",
    "Distrito Capital",
    "Falcón",
    "Guárico",
    "Lara",
    "Miranda",
    "Monagas",
    "Mérida",
    "Nueva Esparta",
    "Portuguesa",
    "Sucre",
    "Trujillo",
    "Táchira",
    "Vargas",
    "Yaracuy",
    "Zulia"
  ],
  "VN" => [
    "An Giang",
    "Bà Rịa-Vũng Tàu",
    "Bình Dương",
    "Bình Phước",
    "Bình Thuận",
    "Bình Định",
    "Bạc Liêu",
    "Bắc Giang",
    "Bắc Kạn",
    "Bắc Ninh",
    "Bến Tre",
    "Cao Bằng",
    "Cà Mau",
    "Cần Thơ",
    "Gia Lai",
    "Hà Giang",
    "Hà Nam",
    "Hà Nội",
    "Hà Tây",
    "Hà Tĩnh",
    "Hòa Bình",
    "Hưng Yên",
    "Hải Dương",
    "Hải Phòng",
    "Hậu Giang",
    "Hồ Chí Minh",
    "Khánh Hòa",
    "Kiên Giang",
    "Kon Tum",
    "Lai Châu",
    "Long An",
    "Lào Cai",
    "Lâm Đồng",
    "Lạng Sơn",
    "Nam Định",
    "Nghệ An",
    "Ninh Bình",
    "Ninh Thuận",
    "Phú Thọ",
    "Phú Yên",
    "Quảng Bình",
    "Quảng Nam",
    "Quảng Ngãi",
    "Quảng Ninh",
    "Quảng Trị",
    "Sóc Trăng",
    "Sơn La",
    "Thanh Hóa",
    "Thái Bình",
    "Thái Nguyên",
    "Thừa Thiên-Huế",
    "Tiền Giang",
    "Trà Vinh",
    "Tuyên Quang",
    "Tây Ninh",
    "Vĩnh Long",
    "Vĩnh Phúc",
    "Yên Bái",
    "Điện Biên",
    "Đà Nẵng",
    "Đắk Lắk",
    "Đắk Nông",
    "Đồng Nai",
    "Đồng Tháp"
  ],
  "WF" => [
    "N/A"
  ],
  "EH" => [
    "N/A"
  ],
  "YE" => [
    "'Adan",
    "'Amrān",
    "Abyān",
    "Al Bayḑā'",
    "Al Jawf",
    "Al Mahrah",
    "Al Maḩwīt",
    "Al Ḩudaydah",
    "Aḑ Ḑāli'",
    "Dhamār",
    "Ibb",
    "Laḩij",
    "Ma'rib",
    "Raymah",
    "Shabwah",
    "Tā'izz",
    "Şan'ā'",
    "Şan'ā'",
    "Şā'dah",
    "Ḩajjah",
    "Ḩaḑramawt"
  ],
  "ZM" => [
    "Central",
    "Copperbelt",
    "Eastern",
    "Luapula",
    "Lusaka",
    "North-Western",
    "Northern",
    "Southern",
    "Western"
  ],
  "ZW" => [
    "Bulawayo",
    "Harare",
    "Manicaland",
    "Mashonaland Central",
    "Mashonaland East",
    "Mashonaland West",
    "Masvingo",
    "Matabeleland North",
    "Matabeleland South",
    "Midlands"
  ],
];